// Code generated by ent, DO NOT EDIT.

package group

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the group type in the database.
	Label = "group"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldJoinCode holds the string denoting the join_code field in the database.
	FieldJoinCode = "join_code"
	// FieldJoinCodeValidUntilTimestamp holds the string denoting the join_code_valid_until_timestamp field in the database.
	FieldJoinCodeValidUntilTimestamp = "join_code_valid_until_timestamp"
	// FieldLastUpdatedAtTimestamp holds the string denoting the last_updated_at_timestamp field in the database.
	FieldLastUpdatedAtTimestamp = "last_updated_at_timestamp"
	// FieldSchoolID holds the string denoting the school_id field in the database.
	FieldSchoolID = "school_id"
	// EdgeSchool holds the string denoting the school edge name in mutations.
	EdgeSchool = "school"
	// EdgeUsers holds the string denoting the users edge name in mutations.
	EdgeUsers = "users"
	// EdgeWordLists holds the string denoting the word_lists edge name in mutations.
	EdgeWordLists = "word_lists"
	// EdgeCompetitions holds the string denoting the competitions edge name in mutations.
	EdgeCompetitions = "competitions"
	// Table holds the table name of the group in the database.
	Table = "groups"
	// SchoolTable is the table that holds the school relation/edge.
	SchoolTable = "groups"
	// SchoolInverseTable is the table name for the School entity.
	// It exists in this package in order to avoid circular dependency with the "school" package.
	SchoolInverseTable = "schools"
	// SchoolColumn is the table column denoting the school relation/edge.
	SchoolColumn = "school_id"
	// UsersTable is the table that holds the users relation/edge. The primary key declared below.
	UsersTable = "group_users"
	// UsersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UsersInverseTable = "users"
	// WordListsTable is the table that holds the word_lists relation/edge. The primary key declared below.
	WordListsTable = "word_list_groups"
	// WordListsInverseTable is the table name for the WordList entity.
	// It exists in this package in order to avoid circular dependency with the "wordlist" package.
	WordListsInverseTable = "word_lists"
	// CompetitionsTable is the table that holds the competitions relation/edge. The primary key declared below.
	CompetitionsTable = "competition_groups"
	// CompetitionsInverseTable is the table name for the Competition entity.
	// It exists in this package in order to avoid circular dependency with the "competition" package.
	CompetitionsInverseTable = "competitions"
)

// Columns holds all SQL columns for group fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldJoinCode,
	FieldJoinCodeValidUntilTimestamp,
	FieldLastUpdatedAtTimestamp,
	FieldSchoolID,
}

var (
	// UsersPrimaryKey and UsersColumn2 are the table columns denoting the
	// primary key for the users relation (M2M).
	UsersPrimaryKey = []string{"group_id", "user_id"}
	// WordListsPrimaryKey and WordListsColumn2 are the table columns denoting the
	// primary key for the word_lists relation (M2M).
	WordListsPrimaryKey = []string{"word_list_id", "group_id"}
	// CompetitionsPrimaryKey and CompetitionsColumn2 are the table columns denoting the
	// primary key for the competitions relation (M2M).
	CompetitionsPrimaryKey = []string{"competition_id", "group_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultJoinCodeValidUntilTimestamp holds the default value on creation for the "join_code_valid_until_timestamp" field.
	DefaultJoinCodeValidUntilTimestamp time.Time
	// DefaultLastUpdatedAtTimestamp holds the default value on creation for the "last_updated_at_timestamp" field.
	DefaultLastUpdatedAtTimestamp time.Time
)

// OrderOption defines the ordering options for the Group queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByJoinCode orders the results by the join_code field.
func ByJoinCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJoinCode, opts...).ToFunc()
}

// ByJoinCodeValidUntilTimestamp orders the results by the join_code_valid_until_timestamp field.
func ByJoinCodeValidUntilTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJoinCodeValidUntilTimestamp, opts...).ToFunc()
}

// ByLastUpdatedAtTimestamp orders the results by the last_updated_at_timestamp field.
func ByLastUpdatedAtTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUpdatedAtTimestamp, opts...).ToFunc()
}

// BySchoolID orders the results by the school_id field.
func BySchoolID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSchoolID, opts...).ToFunc()
}

// BySchoolField orders the results by school field.
func BySchoolField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSchoolStep(), sql.OrderByField(field, opts...))
	}
}

// ByUsersCount orders the results by users count.
func ByUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUsersStep(), opts...)
	}
}

// ByUsers orders the results by users terms.
func ByUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByWordListsCount orders the results by word_lists count.
func ByWordListsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newWordListsStep(), opts...)
	}
}

// ByWordLists orders the results by word_lists terms.
func ByWordLists(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWordListsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCompetitionsCount orders the results by competitions count.
func ByCompetitionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCompetitionsStep(), opts...)
	}
}

// ByCompetitions orders the results by competitions terms.
func ByCompetitions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCompetitionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSchoolStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SchoolInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SchoolTable, SchoolColumn),
	)
}
func newUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, UsersTable, UsersPrimaryKey...),
	)
}
func newWordListsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WordListsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, WordListsTable, WordListsPrimaryKey...),
	)
}
func newCompetitionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CompetitionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, CompetitionsTable, CompetitionsPrimaryKey...),
	)
}
