// Code generated by ent, DO NOT EDIT.

package competition

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the competition type in the database.
	Label = "competition"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldStartTimestamp holds the string denoting the start_timestamp field in the database.
	FieldStartTimestamp = "start_timestamp"
	// FieldEndTimestamp holds the string denoting the end_timestamp field in the database.
	FieldEndTimestamp = "end_timestamp"
	// FieldLastUpdatedAtTimestamp holds the string denoting the last_updated_at_timestamp field in the database.
	FieldLastUpdatedAtTimestamp = "last_updated_at_timestamp"
	// EdgeGroups holds the string denoting the groups edge name in mutations.
	EdgeGroups = "groups"
	// EdgeWordLists holds the string denoting the word_lists edge name in mutations.
	EdgeWordLists = "word_lists"
	// Table holds the table name of the competition in the database.
	Table = "competitions"
	// GroupsTable is the table that holds the groups relation/edge. The primary key declared below.
	GroupsTable = "competition_groups"
	// GroupsInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupsInverseTable = "groups"
	// WordListsTable is the table that holds the word_lists relation/edge. The primary key declared below.
	WordListsTable = "competition_word_lists"
	// WordListsInverseTable is the table name for the WordList entity.
	// It exists in this package in order to avoid circular dependency with the "wordlist" package.
	WordListsInverseTable = "word_lists"
)

// Columns holds all SQL columns for competition fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldType,
	FieldStartTimestamp,
	FieldEndTimestamp,
	FieldLastUpdatedAtTimestamp,
}

var (
	// GroupsPrimaryKey and GroupsColumn2 are the table columns denoting the
	// primary key for the groups relation (M2M).
	GroupsPrimaryKey = []string{"competition_id", "group_id"}
	// WordListsPrimaryKey and WordListsColumn2 are the table columns denoting the
	// primary key for the word_lists relation (M2M).
	WordListsPrimaryKey = []string{"competition_id", "word_list_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultType holds the default value on creation for the "type" field.
	DefaultType string
	// DefaultStartTimestamp holds the default value on creation for the "start_timestamp" field.
	DefaultStartTimestamp time.Time
	// DefaultEndTimestamp holds the default value on creation for the "end_timestamp" field.
	DefaultEndTimestamp time.Time
	// DefaultLastUpdatedAtTimestamp holds the default value on creation for the "last_updated_at_timestamp" field.
	DefaultLastUpdatedAtTimestamp time.Time
)

// OrderOption defines the ordering options for the Competition queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByStartTimestamp orders the results by the start_timestamp field.
func ByStartTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartTimestamp, opts...).ToFunc()
}

// ByEndTimestamp orders the results by the end_timestamp field.
func ByEndTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndTimestamp, opts...).ToFunc()
}

// ByLastUpdatedAtTimestamp orders the results by the last_updated_at_timestamp field.
func ByLastUpdatedAtTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUpdatedAtTimestamp, opts...).ToFunc()
}

// ByGroupsCount orders the results by groups count.
func ByGroupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGroupsStep(), opts...)
	}
}

// ByGroups orders the results by groups terms.
func ByGroups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByWordListsCount orders the results by word_lists count.
func ByWordListsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newWordListsStep(), opts...)
	}
}

// ByWordLists orders the results by word_lists terms.
func ByWordLists(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWordListsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, GroupsTable, GroupsPrimaryKey...),
	)
}
func newWordListsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WordListsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, WordListsTable, WordListsPrimaryKey...),
	)
}
