// Code generated by ent, DO NOT EDIT.

package competition

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/PhilAldridge/spell-api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Competition {
	return predicate.Competition(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Competition {
	return predicate.Competition(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Competition {
	return predicate.Competition(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Competition {
	return predicate.Competition(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Competition {
	return predicate.Competition(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Competition {
	return predicate.Competition(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Competition {
	return predicate.Competition(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Competition {
	return predicate.Competition(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Competition {
	return predicate.Competition(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Competition {
	return predicate.Competition(sql.FieldEQ(FieldName, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Competition {
	return predicate.Competition(sql.FieldEQ(FieldType, v))
}

// StartTimestamp applies equality check predicate on the "start_timestamp" field. It's identical to StartTimestampEQ.
func StartTimestamp(v time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldEQ(FieldStartTimestamp, v))
}

// EndTimestamp applies equality check predicate on the "end_timestamp" field. It's identical to EndTimestampEQ.
func EndTimestamp(v time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldEQ(FieldEndTimestamp, v))
}

// LastUpdatedAtTimestamp applies equality check predicate on the "last_updated_at_timestamp" field. It's identical to LastUpdatedAtTimestampEQ.
func LastUpdatedAtTimestamp(v time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldEQ(FieldLastUpdatedAtTimestamp, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Competition {
	return predicate.Competition(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Competition {
	return predicate.Competition(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Competition {
	return predicate.Competition(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Competition {
	return predicate.Competition(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Competition {
	return predicate.Competition(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Competition {
	return predicate.Competition(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Competition {
	return predicate.Competition(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Competition {
	return predicate.Competition(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Competition {
	return predicate.Competition(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Competition {
	return predicate.Competition(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Competition {
	return predicate.Competition(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Competition {
	return predicate.Competition(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Competition {
	return predicate.Competition(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Competition {
	return predicate.Competition(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Competition {
	return predicate.Competition(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Competition {
	return predicate.Competition(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Competition {
	return predicate.Competition(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Competition {
	return predicate.Competition(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Competition {
	return predicate.Competition(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Competition {
	return predicate.Competition(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Competition {
	return predicate.Competition(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Competition {
	return predicate.Competition(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Competition {
	return predicate.Competition(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Competition {
	return predicate.Competition(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Competition {
	return predicate.Competition(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Competition {
	return predicate.Competition(sql.FieldContainsFold(FieldType, v))
}

// StartTimestampEQ applies the EQ predicate on the "start_timestamp" field.
func StartTimestampEQ(v time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldEQ(FieldStartTimestamp, v))
}

// StartTimestampNEQ applies the NEQ predicate on the "start_timestamp" field.
func StartTimestampNEQ(v time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldNEQ(FieldStartTimestamp, v))
}

// StartTimestampIn applies the In predicate on the "start_timestamp" field.
func StartTimestampIn(vs ...time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldIn(FieldStartTimestamp, vs...))
}

// StartTimestampNotIn applies the NotIn predicate on the "start_timestamp" field.
func StartTimestampNotIn(vs ...time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldNotIn(FieldStartTimestamp, vs...))
}

// StartTimestampGT applies the GT predicate on the "start_timestamp" field.
func StartTimestampGT(v time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldGT(FieldStartTimestamp, v))
}

// StartTimestampGTE applies the GTE predicate on the "start_timestamp" field.
func StartTimestampGTE(v time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldGTE(FieldStartTimestamp, v))
}

// StartTimestampLT applies the LT predicate on the "start_timestamp" field.
func StartTimestampLT(v time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldLT(FieldStartTimestamp, v))
}

// StartTimestampLTE applies the LTE predicate on the "start_timestamp" field.
func StartTimestampLTE(v time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldLTE(FieldStartTimestamp, v))
}

// EndTimestampEQ applies the EQ predicate on the "end_timestamp" field.
func EndTimestampEQ(v time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldEQ(FieldEndTimestamp, v))
}

// EndTimestampNEQ applies the NEQ predicate on the "end_timestamp" field.
func EndTimestampNEQ(v time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldNEQ(FieldEndTimestamp, v))
}

// EndTimestampIn applies the In predicate on the "end_timestamp" field.
func EndTimestampIn(vs ...time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldIn(FieldEndTimestamp, vs...))
}

// EndTimestampNotIn applies the NotIn predicate on the "end_timestamp" field.
func EndTimestampNotIn(vs ...time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldNotIn(FieldEndTimestamp, vs...))
}

// EndTimestampGT applies the GT predicate on the "end_timestamp" field.
func EndTimestampGT(v time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldGT(FieldEndTimestamp, v))
}

// EndTimestampGTE applies the GTE predicate on the "end_timestamp" field.
func EndTimestampGTE(v time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldGTE(FieldEndTimestamp, v))
}

// EndTimestampLT applies the LT predicate on the "end_timestamp" field.
func EndTimestampLT(v time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldLT(FieldEndTimestamp, v))
}

// EndTimestampLTE applies the LTE predicate on the "end_timestamp" field.
func EndTimestampLTE(v time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldLTE(FieldEndTimestamp, v))
}

// LastUpdatedAtTimestampEQ applies the EQ predicate on the "last_updated_at_timestamp" field.
func LastUpdatedAtTimestampEQ(v time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldEQ(FieldLastUpdatedAtTimestamp, v))
}

// LastUpdatedAtTimestampNEQ applies the NEQ predicate on the "last_updated_at_timestamp" field.
func LastUpdatedAtTimestampNEQ(v time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldNEQ(FieldLastUpdatedAtTimestamp, v))
}

// LastUpdatedAtTimestampIn applies the In predicate on the "last_updated_at_timestamp" field.
func LastUpdatedAtTimestampIn(vs ...time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldIn(FieldLastUpdatedAtTimestamp, vs...))
}

// LastUpdatedAtTimestampNotIn applies the NotIn predicate on the "last_updated_at_timestamp" field.
func LastUpdatedAtTimestampNotIn(vs ...time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldNotIn(FieldLastUpdatedAtTimestamp, vs...))
}

// LastUpdatedAtTimestampGT applies the GT predicate on the "last_updated_at_timestamp" field.
func LastUpdatedAtTimestampGT(v time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldGT(FieldLastUpdatedAtTimestamp, v))
}

// LastUpdatedAtTimestampGTE applies the GTE predicate on the "last_updated_at_timestamp" field.
func LastUpdatedAtTimestampGTE(v time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldGTE(FieldLastUpdatedAtTimestamp, v))
}

// LastUpdatedAtTimestampLT applies the LT predicate on the "last_updated_at_timestamp" field.
func LastUpdatedAtTimestampLT(v time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldLT(FieldLastUpdatedAtTimestamp, v))
}

// LastUpdatedAtTimestampLTE applies the LTE predicate on the "last_updated_at_timestamp" field.
func LastUpdatedAtTimestampLTE(v time.Time) predicate.Competition {
	return predicate.Competition(sql.FieldLTE(FieldLastUpdatedAtTimestamp, v))
}

// HasGroups applies the HasEdge predicate on the "groups" edge.
func HasGroups() predicate.Competition {
	return predicate.Competition(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, GroupsTable, GroupsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupsWith applies the HasEdge predicate on the "groups" edge with a given conditions (other predicates).
func HasGroupsWith(preds ...predicate.Group) predicate.Competition {
	return predicate.Competition(func(s *sql.Selector) {
		step := newGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWordLists applies the HasEdge predicate on the "word_lists" edge.
func HasWordLists() predicate.Competition {
	return predicate.Competition(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, WordListsTable, WordListsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWordListsWith applies the HasEdge predicate on the "word_lists" edge with a given conditions (other predicates).
func HasWordListsWith(preds ...predicate.WordList) predicate.Competition {
	return predicate.Competition(func(s *sql.Selector) {
		step := newWordListsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Competition) predicate.Competition {
	return predicate.Competition(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Competition) predicate.Competition {
	return predicate.Competition(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Competition) predicate.Competition {
	return predicate.Competition(sql.NotPredicates(p))
}
