// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PhilAldridge/spell-api/ent/competition"
	"github.com/PhilAldridge/spell-api/ent/group"
	"github.com/PhilAldridge/spell-api/ent/predicate"
	"github.com/PhilAldridge/spell-api/ent/wordlist"
)

// CompetitionQuery is the builder for querying Competition entities.
type CompetitionQuery struct {
	config
	ctx           *QueryContext
	order         []competition.OrderOption
	inters        []Interceptor
	predicates    []predicate.Competition
	withGroups    *GroupQuery
	withWordLists *WordListQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CompetitionQuery builder.
func (_q *CompetitionQuery) Where(ps ...predicate.Competition) *CompetitionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CompetitionQuery) Limit(limit int) *CompetitionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CompetitionQuery) Offset(offset int) *CompetitionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CompetitionQuery) Unique(unique bool) *CompetitionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CompetitionQuery) Order(o ...competition.OrderOption) *CompetitionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryGroups chains the current query on the "groups" edge.
func (_q *CompetitionQuery) QueryGroups() *GroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(competition.Table, competition.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, competition.GroupsTable, competition.GroupsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWordLists chains the current query on the "word_lists" edge.
func (_q *CompetitionQuery) QueryWordLists() *WordListQuery {
	query := (&WordListClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(competition.Table, competition.FieldID, selector),
			sqlgraph.To(wordlist.Table, wordlist.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, competition.WordListsTable, competition.WordListsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Competition entity from the query.
// Returns a *NotFoundError when no Competition was found.
func (_q *CompetitionQuery) First(ctx context.Context) (*Competition, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{competition.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CompetitionQuery) FirstX(ctx context.Context) *Competition {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Competition ID from the query.
// Returns a *NotFoundError when no Competition ID was found.
func (_q *CompetitionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{competition.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CompetitionQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Competition entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Competition entity is found.
// Returns a *NotFoundError when no Competition entities are found.
func (_q *CompetitionQuery) Only(ctx context.Context) (*Competition, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{competition.Label}
	default:
		return nil, &NotSingularError{competition.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CompetitionQuery) OnlyX(ctx context.Context) *Competition {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Competition ID in the query.
// Returns a *NotSingularError when more than one Competition ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CompetitionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{competition.Label}
	default:
		err = &NotSingularError{competition.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CompetitionQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Competitions.
func (_q *CompetitionQuery) All(ctx context.Context) ([]*Competition, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Competition, *CompetitionQuery]()
	return withInterceptors[[]*Competition](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CompetitionQuery) AllX(ctx context.Context) []*Competition {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Competition IDs.
func (_q *CompetitionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(competition.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CompetitionQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CompetitionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CompetitionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CompetitionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CompetitionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CompetitionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CompetitionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CompetitionQuery) Clone() *CompetitionQuery {
	if _q == nil {
		return nil
	}
	return &CompetitionQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]competition.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.Competition{}, _q.predicates...),
		withGroups:    _q.withGroups.Clone(),
		withWordLists: _q.withWordLists.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithGroups tells the query-builder to eager-load the nodes that are connected to
// the "groups" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CompetitionQuery) WithGroups(opts ...func(*GroupQuery)) *CompetitionQuery {
	query := (&GroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroups = query
	return _q
}

// WithWordLists tells the query-builder to eager-load the nodes that are connected to
// the "word_lists" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CompetitionQuery) WithWordLists(opts ...func(*WordListQuery)) *CompetitionQuery {
	query := (&WordListClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWordLists = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Competition.Query().
//		GroupBy(competition.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CompetitionQuery) GroupBy(field string, fields ...string) *CompetitionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CompetitionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = competition.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Competition.Query().
//		Select(competition.FieldName).
//		Scan(ctx, &v)
func (_q *CompetitionQuery) Select(fields ...string) *CompetitionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CompetitionSelect{CompetitionQuery: _q}
	sbuild.label = competition.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CompetitionSelect configured with the given aggregations.
func (_q *CompetitionQuery) Aggregate(fns ...AggregateFunc) *CompetitionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CompetitionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !competition.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CompetitionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Competition, error) {
	var (
		nodes       = []*Competition{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withGroups != nil,
			_q.withWordLists != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Competition).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Competition{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withGroups; query != nil {
		if err := _q.loadGroups(ctx, query, nodes,
			func(n *Competition) { n.Edges.Groups = []*Group{} },
			func(n *Competition, e *Group) { n.Edges.Groups = append(n.Edges.Groups, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withWordLists; query != nil {
		if err := _q.loadWordLists(ctx, query, nodes,
			func(n *Competition) { n.Edges.WordLists = []*WordList{} },
			func(n *Competition, e *WordList) { n.Edges.WordLists = append(n.Edges.WordLists, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CompetitionQuery) loadGroups(ctx context.Context, query *GroupQuery, nodes []*Competition, init func(*Competition), assign func(*Competition, *Group)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Competition)
	nids := make(map[int]map[*Competition]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(competition.GroupsTable)
		s.Join(joinT).On(s.C(group.FieldID), joinT.C(competition.GroupsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(competition.GroupsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(competition.GroupsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Competition]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Group](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "groups" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *CompetitionQuery) loadWordLists(ctx context.Context, query *WordListQuery, nodes []*Competition, init func(*Competition), assign func(*Competition, *WordList)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Competition)
	nids := make(map[int]map[*Competition]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(competition.WordListsTable)
		s.Join(joinT).On(s.C(wordlist.FieldID), joinT.C(competition.WordListsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(competition.WordListsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(competition.WordListsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Competition]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*WordList](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "word_lists" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (_q *CompetitionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CompetitionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(competition.Table, competition.Columns, sqlgraph.NewFieldSpec(competition.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, competition.FieldID)
		for i := range fields {
			if fields[i] != competition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CompetitionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(competition.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = competition.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CompetitionGroupBy is the group-by builder for Competition entities.
type CompetitionGroupBy struct {
	selector
	build *CompetitionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CompetitionGroupBy) Aggregate(fns ...AggregateFunc) *CompetitionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CompetitionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CompetitionQuery, *CompetitionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CompetitionGroupBy) sqlScan(ctx context.Context, root *CompetitionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CompetitionSelect is the builder for selecting fields of Competition entities.
type CompetitionSelect struct {
	*CompetitionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CompetitionSelect) Aggregate(fns ...AggregateFunc) *CompetitionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CompetitionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CompetitionQuery, *CompetitionSelect](ctx, _s.CompetitionQuery, _s, _s.inters, v)
}

func (_s *CompetitionSelect) sqlScan(ctx context.Context, root *CompetitionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
