// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/PhilAldridge/spell-api/ent/competition"
)

// Competition is the model entity for the Competition schema.
type Competition struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// StartTimestamp holds the value of the "start_timestamp" field.
	StartTimestamp time.Time `json:"start_timestamp,omitempty"`
	// EndTimestamp holds the value of the "end_timestamp" field.
	EndTimestamp time.Time `json:"end_timestamp,omitempty"`
	// LastUpdatedAtTimestamp holds the value of the "last_updated_at_timestamp" field.
	LastUpdatedAtTimestamp time.Time `json:"last_updated_at_timestamp,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CompetitionQuery when eager-loading is set.
	Edges        CompetitionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CompetitionEdges holds the relations/edges for other nodes in the graph.
type CompetitionEdges struct {
	// Groups holds the value of the groups edge.
	Groups []*Group `json:"groups,omitempty"`
	// WordLists holds the value of the word_lists edge.
	WordLists []*WordList `json:"word_lists,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GroupsOrErr returns the Groups value or an error if the edge
// was not loaded in eager-loading.
func (e CompetitionEdges) GroupsOrErr() ([]*Group, error) {
	if e.loadedTypes[0] {
		return e.Groups, nil
	}
	return nil, &NotLoadedError{edge: "groups"}
}

// WordListsOrErr returns the WordLists value or an error if the edge
// was not loaded in eager-loading.
func (e CompetitionEdges) WordListsOrErr() ([]*WordList, error) {
	if e.loadedTypes[1] {
		return e.WordLists, nil
	}
	return nil, &NotLoadedError{edge: "word_lists"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Competition) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case competition.FieldID:
			values[i] = new(sql.NullInt64)
		case competition.FieldName, competition.FieldType:
			values[i] = new(sql.NullString)
		case competition.FieldStartTimestamp, competition.FieldEndTimestamp, competition.FieldLastUpdatedAtTimestamp:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Competition fields.
func (_m *Competition) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case competition.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case competition.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case competition.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case competition.FieldStartTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_timestamp", values[i])
			} else if value.Valid {
				_m.StartTimestamp = value.Time
			}
		case competition.FieldEndTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_timestamp", values[i])
			} else if value.Valid {
				_m.EndTimestamp = value.Time
			}
		case competition.FieldLastUpdatedAtTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_updated_at_timestamp", values[i])
			} else if value.Valid {
				_m.LastUpdatedAtTimestamp = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Competition.
// This includes values selected through modifiers, order, etc.
func (_m *Competition) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroups queries the "groups" edge of the Competition entity.
func (_m *Competition) QueryGroups() *GroupQuery {
	return NewCompetitionClient(_m.config).QueryGroups(_m)
}

// QueryWordLists queries the "word_lists" edge of the Competition entity.
func (_m *Competition) QueryWordLists() *WordListQuery {
	return NewCompetitionClient(_m.config).QueryWordLists(_m)
}

// Update returns a builder for updating this Competition.
// Note that you need to call Competition.Unwrap() before calling this method if this Competition
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Competition) Update() *CompetitionUpdateOne {
	return NewCompetitionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Competition entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Competition) Unwrap() *Competition {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Competition is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Competition) String() string {
	var builder strings.Builder
	builder.WriteString("Competition(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("start_timestamp=")
	builder.WriteString(_m.StartTimestamp.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("end_timestamp=")
	builder.WriteString(_m.EndTimestamp.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_updated_at_timestamp=")
	builder.WriteString(_m.LastUpdatedAtTimestamp.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Competitions is a parsable slice of Competition.
type Competitions []*Competition
