// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PhilAldridge/spell-api/ent/competition"
	"github.com/PhilAldridge/spell-api/ent/group"
	"github.com/PhilAldridge/spell-api/ent/predicate"
	"github.com/PhilAldridge/spell-api/ent/wordlist"
)

// CompetitionUpdate is the builder for updating Competition entities.
type CompetitionUpdate struct {
	config
	hooks    []Hook
	mutation *CompetitionMutation
}

// Where appends a list predicates to the CompetitionUpdate builder.
func (_u *CompetitionUpdate) Where(ps ...predicate.Competition) *CompetitionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *CompetitionUpdate) SetName(v string) *CompetitionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CompetitionUpdate) SetNillableName(v *string) *CompetitionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *CompetitionUpdate) SetType(v string) *CompetitionUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *CompetitionUpdate) SetNillableType(v *string) *CompetitionUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStartTimestamp sets the "start_timestamp" field.
func (_u *CompetitionUpdate) SetStartTimestamp(v time.Time) *CompetitionUpdate {
	_u.mutation.SetStartTimestamp(v)
	return _u
}

// SetNillableStartTimestamp sets the "start_timestamp" field if the given value is not nil.
func (_u *CompetitionUpdate) SetNillableStartTimestamp(v *time.Time) *CompetitionUpdate {
	if v != nil {
		_u.SetStartTimestamp(*v)
	}
	return _u
}

// SetEndTimestamp sets the "end_timestamp" field.
func (_u *CompetitionUpdate) SetEndTimestamp(v time.Time) *CompetitionUpdate {
	_u.mutation.SetEndTimestamp(v)
	return _u
}

// SetNillableEndTimestamp sets the "end_timestamp" field if the given value is not nil.
func (_u *CompetitionUpdate) SetNillableEndTimestamp(v *time.Time) *CompetitionUpdate {
	if v != nil {
		_u.SetEndTimestamp(*v)
	}
	return _u
}

// SetLastUpdatedAtTimestamp sets the "last_updated_at_timestamp" field.
func (_u *CompetitionUpdate) SetLastUpdatedAtTimestamp(v time.Time) *CompetitionUpdate {
	_u.mutation.SetLastUpdatedAtTimestamp(v)
	return _u
}

// SetNillableLastUpdatedAtTimestamp sets the "last_updated_at_timestamp" field if the given value is not nil.
func (_u *CompetitionUpdate) SetNillableLastUpdatedAtTimestamp(v *time.Time) *CompetitionUpdate {
	if v != nil {
		_u.SetLastUpdatedAtTimestamp(*v)
	}
	return _u
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_u *CompetitionUpdate) AddGroupIDs(ids ...int) *CompetitionUpdate {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the Group entity.
func (_u *CompetitionUpdate) AddGroups(v ...*Group) *CompetitionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// AddWordListIDs adds the "word_lists" edge to the WordList entity by IDs.
func (_u *CompetitionUpdate) AddWordListIDs(ids ...int) *CompetitionUpdate {
	_u.mutation.AddWordListIDs(ids...)
	return _u
}

// AddWordLists adds the "word_lists" edges to the WordList entity.
func (_u *CompetitionUpdate) AddWordLists(v ...*WordList) *CompetitionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWordListIDs(ids...)
}

// Mutation returns the CompetitionMutation object of the builder.
func (_u *CompetitionUpdate) Mutation() *CompetitionMutation {
	return _u.mutation
}

// ClearGroups clears all "groups" edges to the Group entity.
func (_u *CompetitionUpdate) ClearGroups() *CompetitionUpdate {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (_u *CompetitionUpdate) RemoveGroupIDs(ids ...int) *CompetitionUpdate {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to Group entities.
func (_u *CompetitionUpdate) RemoveGroups(v ...*Group) *CompetitionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearWordLists clears all "word_lists" edges to the WordList entity.
func (_u *CompetitionUpdate) ClearWordLists() *CompetitionUpdate {
	_u.mutation.ClearWordLists()
	return _u
}

// RemoveWordListIDs removes the "word_lists" edge to WordList entities by IDs.
func (_u *CompetitionUpdate) RemoveWordListIDs(ids ...int) *CompetitionUpdate {
	_u.mutation.RemoveWordListIDs(ids...)
	return _u
}

// RemoveWordLists removes "word_lists" edges to WordList entities.
func (_u *CompetitionUpdate) RemoveWordLists(v ...*WordList) *CompetitionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWordListIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CompetitionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CompetitionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CompetitionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CompetitionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CompetitionUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := competition.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Competition.name": %w`, err)}
		}
	}
	return nil
}

func (_u *CompetitionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(competition.Table, competition.Columns, sqlgraph.NewFieldSpec(competition.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(competition.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(competition.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartTimestamp(); ok {
		_spec.SetField(competition.FieldStartTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndTimestamp(); ok {
		_spec.SetField(competition.FieldEndTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastUpdatedAtTimestamp(); ok {
		_spec.SetField(competition.FieldLastUpdatedAtTimestamp, field.TypeTime, value)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   competition.GroupsTable,
			Columns: competition.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   competition.GroupsTable,
			Columns: competition.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   competition.GroupsTable,
			Columns: competition.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WordListsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   competition.WordListsTable,
			Columns: competition.WordListsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWordListsIDs(); len(nodes) > 0 && !_u.mutation.WordListsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   competition.WordListsTable,
			Columns: competition.WordListsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WordListsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   competition.WordListsTable,
			Columns: competition.WordListsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{competition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CompetitionUpdateOne is the builder for updating a single Competition entity.
type CompetitionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CompetitionMutation
}

// SetName sets the "name" field.
func (_u *CompetitionUpdateOne) SetName(v string) *CompetitionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CompetitionUpdateOne) SetNillableName(v *string) *CompetitionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *CompetitionUpdateOne) SetType(v string) *CompetitionUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *CompetitionUpdateOne) SetNillableType(v *string) *CompetitionUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStartTimestamp sets the "start_timestamp" field.
func (_u *CompetitionUpdateOne) SetStartTimestamp(v time.Time) *CompetitionUpdateOne {
	_u.mutation.SetStartTimestamp(v)
	return _u
}

// SetNillableStartTimestamp sets the "start_timestamp" field if the given value is not nil.
func (_u *CompetitionUpdateOne) SetNillableStartTimestamp(v *time.Time) *CompetitionUpdateOne {
	if v != nil {
		_u.SetStartTimestamp(*v)
	}
	return _u
}

// SetEndTimestamp sets the "end_timestamp" field.
func (_u *CompetitionUpdateOne) SetEndTimestamp(v time.Time) *CompetitionUpdateOne {
	_u.mutation.SetEndTimestamp(v)
	return _u
}

// SetNillableEndTimestamp sets the "end_timestamp" field if the given value is not nil.
func (_u *CompetitionUpdateOne) SetNillableEndTimestamp(v *time.Time) *CompetitionUpdateOne {
	if v != nil {
		_u.SetEndTimestamp(*v)
	}
	return _u
}

// SetLastUpdatedAtTimestamp sets the "last_updated_at_timestamp" field.
func (_u *CompetitionUpdateOne) SetLastUpdatedAtTimestamp(v time.Time) *CompetitionUpdateOne {
	_u.mutation.SetLastUpdatedAtTimestamp(v)
	return _u
}

// SetNillableLastUpdatedAtTimestamp sets the "last_updated_at_timestamp" field if the given value is not nil.
func (_u *CompetitionUpdateOne) SetNillableLastUpdatedAtTimestamp(v *time.Time) *CompetitionUpdateOne {
	if v != nil {
		_u.SetLastUpdatedAtTimestamp(*v)
	}
	return _u
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_u *CompetitionUpdateOne) AddGroupIDs(ids ...int) *CompetitionUpdateOne {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the Group entity.
func (_u *CompetitionUpdateOne) AddGroups(v ...*Group) *CompetitionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// AddWordListIDs adds the "word_lists" edge to the WordList entity by IDs.
func (_u *CompetitionUpdateOne) AddWordListIDs(ids ...int) *CompetitionUpdateOne {
	_u.mutation.AddWordListIDs(ids...)
	return _u
}

// AddWordLists adds the "word_lists" edges to the WordList entity.
func (_u *CompetitionUpdateOne) AddWordLists(v ...*WordList) *CompetitionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWordListIDs(ids...)
}

// Mutation returns the CompetitionMutation object of the builder.
func (_u *CompetitionUpdateOne) Mutation() *CompetitionMutation {
	return _u.mutation
}

// ClearGroups clears all "groups" edges to the Group entity.
func (_u *CompetitionUpdateOne) ClearGroups() *CompetitionUpdateOne {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (_u *CompetitionUpdateOne) RemoveGroupIDs(ids ...int) *CompetitionUpdateOne {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to Group entities.
func (_u *CompetitionUpdateOne) RemoveGroups(v ...*Group) *CompetitionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearWordLists clears all "word_lists" edges to the WordList entity.
func (_u *CompetitionUpdateOne) ClearWordLists() *CompetitionUpdateOne {
	_u.mutation.ClearWordLists()
	return _u
}

// RemoveWordListIDs removes the "word_lists" edge to WordList entities by IDs.
func (_u *CompetitionUpdateOne) RemoveWordListIDs(ids ...int) *CompetitionUpdateOne {
	_u.mutation.RemoveWordListIDs(ids...)
	return _u
}

// RemoveWordLists removes "word_lists" edges to WordList entities.
func (_u *CompetitionUpdateOne) RemoveWordLists(v ...*WordList) *CompetitionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWordListIDs(ids...)
}

// Where appends a list predicates to the CompetitionUpdate builder.
func (_u *CompetitionUpdateOne) Where(ps ...predicate.Competition) *CompetitionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CompetitionUpdateOne) Select(field string, fields ...string) *CompetitionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Competition entity.
func (_u *CompetitionUpdateOne) Save(ctx context.Context) (*Competition, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CompetitionUpdateOne) SaveX(ctx context.Context) *Competition {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CompetitionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CompetitionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CompetitionUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := competition.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Competition.name": %w`, err)}
		}
	}
	return nil
}

func (_u *CompetitionUpdateOne) sqlSave(ctx context.Context) (_node *Competition, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(competition.Table, competition.Columns, sqlgraph.NewFieldSpec(competition.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Competition.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, competition.FieldID)
		for _, f := range fields {
			if !competition.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != competition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(competition.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(competition.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartTimestamp(); ok {
		_spec.SetField(competition.FieldStartTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndTimestamp(); ok {
		_spec.SetField(competition.FieldEndTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastUpdatedAtTimestamp(); ok {
		_spec.SetField(competition.FieldLastUpdatedAtTimestamp, field.TypeTime, value)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   competition.GroupsTable,
			Columns: competition.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   competition.GroupsTable,
			Columns: competition.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   competition.GroupsTable,
			Columns: competition.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WordListsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   competition.WordListsTable,
			Columns: competition.WordListsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWordListsIDs(); len(nodes) > 0 && !_u.mutation.WordListsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   competition.WordListsTable,
			Columns: competition.WordListsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WordListsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   competition.WordListsTable,
			Columns: competition.WordListsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Competition{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{competition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
