// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PhilAldridge/spell-api/ent/competition"
	"github.com/PhilAldridge/spell-api/ent/group"
	"github.com/PhilAldridge/spell-api/ent/wordlist"
)

// CompetitionCreate is the builder for creating a Competition entity.
type CompetitionCreate struct {
	config
	mutation *CompetitionMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *CompetitionCreate) SetName(v string) *CompetitionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetType sets the "type" field.
func (_c *CompetitionCreate) SetType(v string) *CompetitionCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *CompetitionCreate) SetNillableType(v *string) *CompetitionCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetStartTimestamp sets the "start_timestamp" field.
func (_c *CompetitionCreate) SetStartTimestamp(v time.Time) *CompetitionCreate {
	_c.mutation.SetStartTimestamp(v)
	return _c
}

// SetNillableStartTimestamp sets the "start_timestamp" field if the given value is not nil.
func (_c *CompetitionCreate) SetNillableStartTimestamp(v *time.Time) *CompetitionCreate {
	if v != nil {
		_c.SetStartTimestamp(*v)
	}
	return _c
}

// SetEndTimestamp sets the "end_timestamp" field.
func (_c *CompetitionCreate) SetEndTimestamp(v time.Time) *CompetitionCreate {
	_c.mutation.SetEndTimestamp(v)
	return _c
}

// SetNillableEndTimestamp sets the "end_timestamp" field if the given value is not nil.
func (_c *CompetitionCreate) SetNillableEndTimestamp(v *time.Time) *CompetitionCreate {
	if v != nil {
		_c.SetEndTimestamp(*v)
	}
	return _c
}

// SetLastUpdatedAtTimestamp sets the "last_updated_at_timestamp" field.
func (_c *CompetitionCreate) SetLastUpdatedAtTimestamp(v time.Time) *CompetitionCreate {
	_c.mutation.SetLastUpdatedAtTimestamp(v)
	return _c
}

// SetNillableLastUpdatedAtTimestamp sets the "last_updated_at_timestamp" field if the given value is not nil.
func (_c *CompetitionCreate) SetNillableLastUpdatedAtTimestamp(v *time.Time) *CompetitionCreate {
	if v != nil {
		_c.SetLastUpdatedAtTimestamp(*v)
	}
	return _c
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_c *CompetitionCreate) AddGroupIDs(ids ...int) *CompetitionCreate {
	_c.mutation.AddGroupIDs(ids...)
	return _c
}

// AddGroups adds the "groups" edges to the Group entity.
func (_c *CompetitionCreate) AddGroups(v ...*Group) *CompetitionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddGroupIDs(ids...)
}

// AddWordListIDs adds the "word_lists" edge to the WordList entity by IDs.
func (_c *CompetitionCreate) AddWordListIDs(ids ...int) *CompetitionCreate {
	_c.mutation.AddWordListIDs(ids...)
	return _c
}

// AddWordLists adds the "word_lists" edges to the WordList entity.
func (_c *CompetitionCreate) AddWordLists(v ...*WordList) *CompetitionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddWordListIDs(ids...)
}

// Mutation returns the CompetitionMutation object of the builder.
func (_c *CompetitionCreate) Mutation() *CompetitionMutation {
	return _c.mutation
}

// Save creates the Competition in the database.
func (_c *CompetitionCreate) Save(ctx context.Context) (*Competition, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CompetitionCreate) SaveX(ctx context.Context) *Competition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CompetitionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CompetitionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CompetitionCreate) defaults() {
	if _, ok := _c.mutation.GetType(); !ok {
		v := competition.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.StartTimestamp(); !ok {
		v := competition.DefaultStartTimestamp
		_c.mutation.SetStartTimestamp(v)
	}
	if _, ok := _c.mutation.EndTimestamp(); !ok {
		v := competition.DefaultEndTimestamp
		_c.mutation.SetEndTimestamp(v)
	}
	if _, ok := _c.mutation.LastUpdatedAtTimestamp(); !ok {
		v := competition.DefaultLastUpdatedAtTimestamp
		_c.mutation.SetLastUpdatedAtTimestamp(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CompetitionCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Competition.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := competition.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Competition.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Competition.type"`)}
	}
	if _, ok := _c.mutation.StartTimestamp(); !ok {
		return &ValidationError{Name: "start_timestamp", err: errors.New(`ent: missing required field "Competition.start_timestamp"`)}
	}
	if _, ok := _c.mutation.EndTimestamp(); !ok {
		return &ValidationError{Name: "end_timestamp", err: errors.New(`ent: missing required field "Competition.end_timestamp"`)}
	}
	if _, ok := _c.mutation.LastUpdatedAtTimestamp(); !ok {
		return &ValidationError{Name: "last_updated_at_timestamp", err: errors.New(`ent: missing required field "Competition.last_updated_at_timestamp"`)}
	}
	return nil
}

func (_c *CompetitionCreate) sqlSave(ctx context.Context) (*Competition, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CompetitionCreate) createSpec() (*Competition, *sqlgraph.CreateSpec) {
	var (
		_node = &Competition{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(competition.Table, sqlgraph.NewFieldSpec(competition.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(competition.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(competition.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.StartTimestamp(); ok {
		_spec.SetField(competition.FieldStartTimestamp, field.TypeTime, value)
		_node.StartTimestamp = value
	}
	if value, ok := _c.mutation.EndTimestamp(); ok {
		_spec.SetField(competition.FieldEndTimestamp, field.TypeTime, value)
		_node.EndTimestamp = value
	}
	if value, ok := _c.mutation.LastUpdatedAtTimestamp(); ok {
		_spec.SetField(competition.FieldLastUpdatedAtTimestamp, field.TypeTime, value)
		_node.LastUpdatedAtTimestamp = value
	}
	if nodes := _c.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   competition.GroupsTable,
			Columns: competition.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WordListsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   competition.WordListsTable,
			Columns: competition.WordListsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CompetitionCreateBulk is the builder for creating many Competition entities in bulk.
type CompetitionCreateBulk struct {
	config
	err      error
	builders []*CompetitionCreate
}

// Save creates the Competition entities in the database.
func (_c *CompetitionCreateBulk) Save(ctx context.Context) ([]*Competition, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Competition, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CompetitionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CompetitionCreateBulk) SaveX(ctx context.Context) []*Competition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CompetitionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CompetitionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
