// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PhilAldridge/spell-api/ent/competition"
	"github.com/PhilAldridge/spell-api/ent/group"
	"github.com/PhilAldridge/spell-api/ent/predicate"
	"github.com/PhilAldridge/spell-api/ent/school"
	"github.com/PhilAldridge/spell-api/ent/user"
	"github.com/PhilAldridge/spell-api/ent/wordlist"
)

// GroupUpdate is the builder for updating Group entities.
type GroupUpdate struct {
	config
	hooks    []Hook
	mutation *GroupMutation
}

// Where appends a list predicates to the GroupUpdate builder.
func (_u *GroupUpdate) Where(ps ...predicate.Group) *GroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *GroupUpdate) SetName(v string) *GroupUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableName(v *string) *GroupUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetJoinCode sets the "join_code" field.
func (_u *GroupUpdate) SetJoinCode(v string) *GroupUpdate {
	_u.mutation.SetJoinCode(v)
	return _u
}

// SetNillableJoinCode sets the "join_code" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableJoinCode(v *string) *GroupUpdate {
	if v != nil {
		_u.SetJoinCode(*v)
	}
	return _u
}

// SetJoinCodeValidUntilTimestamp sets the "join_code_valid_until_timestamp" field.
func (_u *GroupUpdate) SetJoinCodeValidUntilTimestamp(v time.Time) *GroupUpdate {
	_u.mutation.SetJoinCodeValidUntilTimestamp(v)
	return _u
}

// SetNillableJoinCodeValidUntilTimestamp sets the "join_code_valid_until_timestamp" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableJoinCodeValidUntilTimestamp(v *time.Time) *GroupUpdate {
	if v != nil {
		_u.SetJoinCodeValidUntilTimestamp(*v)
	}
	return _u
}

// SetLastUpdatedAtTimestamp sets the "last_updated_at_timestamp" field.
func (_u *GroupUpdate) SetLastUpdatedAtTimestamp(v time.Time) *GroupUpdate {
	_u.mutation.SetLastUpdatedAtTimestamp(v)
	return _u
}

// SetNillableLastUpdatedAtTimestamp sets the "last_updated_at_timestamp" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableLastUpdatedAtTimestamp(v *time.Time) *GroupUpdate {
	if v != nil {
		_u.SetLastUpdatedAtTimestamp(*v)
	}
	return _u
}

// SetSchoolID sets the "school_id" field.
func (_u *GroupUpdate) SetSchoolID(v int) *GroupUpdate {
	_u.mutation.SetSchoolID(v)
	return _u
}

// SetNillableSchoolID sets the "school_id" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableSchoolID(v *int) *GroupUpdate {
	if v != nil {
		_u.SetSchoolID(*v)
	}
	return _u
}

// SetSchool sets the "school" edge to the School entity.
func (_u *GroupUpdate) SetSchool(v *School) *GroupUpdate {
	return _u.SetSchoolID(v.ID)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *GroupUpdate) AddUserIDs(ids ...int) *GroupUpdate {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *GroupUpdate) AddUsers(v ...*User) *GroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// AddWordListIDs adds the "word_lists" edge to the WordList entity by IDs.
func (_u *GroupUpdate) AddWordListIDs(ids ...int) *GroupUpdate {
	_u.mutation.AddWordListIDs(ids...)
	return _u
}

// AddWordLists adds the "word_lists" edges to the WordList entity.
func (_u *GroupUpdate) AddWordLists(v ...*WordList) *GroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWordListIDs(ids...)
}

// AddCompetitionIDs adds the "competitions" edge to the Competition entity by IDs.
func (_u *GroupUpdate) AddCompetitionIDs(ids ...int) *GroupUpdate {
	_u.mutation.AddCompetitionIDs(ids...)
	return _u
}

// AddCompetitions adds the "competitions" edges to the Competition entity.
func (_u *GroupUpdate) AddCompetitions(v ...*Competition) *GroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCompetitionIDs(ids...)
}

// Mutation returns the GroupMutation object of the builder.
func (_u *GroupUpdate) Mutation() *GroupMutation {
	return _u.mutation
}

// ClearSchool clears the "school" edge to the School entity.
func (_u *GroupUpdate) ClearSchool() *GroupUpdate {
	_u.mutation.ClearSchool()
	return _u
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *GroupUpdate) ClearUsers() *GroupUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *GroupUpdate) RemoveUserIDs(ids ...int) *GroupUpdate {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *GroupUpdate) RemoveUsers(v ...*User) *GroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// ClearWordLists clears all "word_lists" edges to the WordList entity.
func (_u *GroupUpdate) ClearWordLists() *GroupUpdate {
	_u.mutation.ClearWordLists()
	return _u
}

// RemoveWordListIDs removes the "word_lists" edge to WordList entities by IDs.
func (_u *GroupUpdate) RemoveWordListIDs(ids ...int) *GroupUpdate {
	_u.mutation.RemoveWordListIDs(ids...)
	return _u
}

// RemoveWordLists removes "word_lists" edges to WordList entities.
func (_u *GroupUpdate) RemoveWordLists(v ...*WordList) *GroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWordListIDs(ids...)
}

// ClearCompetitions clears all "competitions" edges to the Competition entity.
func (_u *GroupUpdate) ClearCompetitions() *GroupUpdate {
	_u.mutation.ClearCompetitions()
	return _u
}

// RemoveCompetitionIDs removes the "competitions" edge to Competition entities by IDs.
func (_u *GroupUpdate) RemoveCompetitionIDs(ids ...int) *GroupUpdate {
	_u.mutation.RemoveCompetitionIDs(ids...)
	return _u
}

// RemoveCompetitions removes "competitions" edges to Competition entities.
func (_u *GroupUpdate) RemoveCompetitions(v ...*Competition) *GroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCompetitionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupUpdate) check() error {
	if v, ok := _u.mutation.JoinCode(); ok {
		if err := group.JoinCodeValidator(v); err != nil {
			return &ValidationError{Name: "join_code", err: fmt.Errorf(`ent: validator failed for field "Group.join_code": %w`, err)}
		}
	}
	if _u.mutation.SchoolCleared() && len(_u.mutation.SchoolIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Group.school"`)
	}
	return nil
}

func (_u *GroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(group.Table, group.Columns, sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(group.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.JoinCode(); ok {
		_spec.SetField(group.FieldJoinCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.JoinCodeValidUntilTimestamp(); ok {
		_spec.SetField(group.FieldJoinCodeValidUntilTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastUpdatedAtTimestamp(); ok {
		_spec.SetField(group.FieldLastUpdatedAtTimestamp, field.TypeTime, value)
	}
	if _u.mutation.SchoolCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   group.SchoolTable,
			Columns: []string{group.SchoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(school.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SchoolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   group.SchoolTable,
			Columns: []string{group.SchoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(school.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   group.UsersTable,
			Columns: group.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   group.UsersTable,
			Columns: group.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   group.UsersTable,
			Columns: group.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WordListsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.WordListsTable,
			Columns: group.WordListsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWordListsIDs(); len(nodes) > 0 && !_u.mutation.WordListsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.WordListsTable,
			Columns: group.WordListsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WordListsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.WordListsTable,
			Columns: group.WordListsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CompetitionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.CompetitionsTable,
			Columns: group.CompetitionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(competition.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCompetitionsIDs(); len(nodes) > 0 && !_u.mutation.CompetitionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.CompetitionsTable,
			Columns: group.CompetitionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(competition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CompetitionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.CompetitionsTable,
			Columns: group.CompetitionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(competition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{group.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroupUpdateOne is the builder for updating a single Group entity.
type GroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupMutation
}

// SetName sets the "name" field.
func (_u *GroupUpdateOne) SetName(v string) *GroupUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableName(v *string) *GroupUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetJoinCode sets the "join_code" field.
func (_u *GroupUpdateOne) SetJoinCode(v string) *GroupUpdateOne {
	_u.mutation.SetJoinCode(v)
	return _u
}

// SetNillableJoinCode sets the "join_code" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableJoinCode(v *string) *GroupUpdateOne {
	if v != nil {
		_u.SetJoinCode(*v)
	}
	return _u
}

// SetJoinCodeValidUntilTimestamp sets the "join_code_valid_until_timestamp" field.
func (_u *GroupUpdateOne) SetJoinCodeValidUntilTimestamp(v time.Time) *GroupUpdateOne {
	_u.mutation.SetJoinCodeValidUntilTimestamp(v)
	return _u
}

// SetNillableJoinCodeValidUntilTimestamp sets the "join_code_valid_until_timestamp" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableJoinCodeValidUntilTimestamp(v *time.Time) *GroupUpdateOne {
	if v != nil {
		_u.SetJoinCodeValidUntilTimestamp(*v)
	}
	return _u
}

// SetLastUpdatedAtTimestamp sets the "last_updated_at_timestamp" field.
func (_u *GroupUpdateOne) SetLastUpdatedAtTimestamp(v time.Time) *GroupUpdateOne {
	_u.mutation.SetLastUpdatedAtTimestamp(v)
	return _u
}

// SetNillableLastUpdatedAtTimestamp sets the "last_updated_at_timestamp" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableLastUpdatedAtTimestamp(v *time.Time) *GroupUpdateOne {
	if v != nil {
		_u.SetLastUpdatedAtTimestamp(*v)
	}
	return _u
}

// SetSchoolID sets the "school_id" field.
func (_u *GroupUpdateOne) SetSchoolID(v int) *GroupUpdateOne {
	_u.mutation.SetSchoolID(v)
	return _u
}

// SetNillableSchoolID sets the "school_id" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableSchoolID(v *int) *GroupUpdateOne {
	if v != nil {
		_u.SetSchoolID(*v)
	}
	return _u
}

// SetSchool sets the "school" edge to the School entity.
func (_u *GroupUpdateOne) SetSchool(v *School) *GroupUpdateOne {
	return _u.SetSchoolID(v.ID)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *GroupUpdateOne) AddUserIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *GroupUpdateOne) AddUsers(v ...*User) *GroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// AddWordListIDs adds the "word_lists" edge to the WordList entity by IDs.
func (_u *GroupUpdateOne) AddWordListIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.AddWordListIDs(ids...)
	return _u
}

// AddWordLists adds the "word_lists" edges to the WordList entity.
func (_u *GroupUpdateOne) AddWordLists(v ...*WordList) *GroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWordListIDs(ids...)
}

// AddCompetitionIDs adds the "competitions" edge to the Competition entity by IDs.
func (_u *GroupUpdateOne) AddCompetitionIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.AddCompetitionIDs(ids...)
	return _u
}

// AddCompetitions adds the "competitions" edges to the Competition entity.
func (_u *GroupUpdateOne) AddCompetitions(v ...*Competition) *GroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCompetitionIDs(ids...)
}

// Mutation returns the GroupMutation object of the builder.
func (_u *GroupUpdateOne) Mutation() *GroupMutation {
	return _u.mutation
}

// ClearSchool clears the "school" edge to the School entity.
func (_u *GroupUpdateOne) ClearSchool() *GroupUpdateOne {
	_u.mutation.ClearSchool()
	return _u
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *GroupUpdateOne) ClearUsers() *GroupUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *GroupUpdateOne) RemoveUserIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *GroupUpdateOne) RemoveUsers(v ...*User) *GroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// ClearWordLists clears all "word_lists" edges to the WordList entity.
func (_u *GroupUpdateOne) ClearWordLists() *GroupUpdateOne {
	_u.mutation.ClearWordLists()
	return _u
}

// RemoveWordListIDs removes the "word_lists" edge to WordList entities by IDs.
func (_u *GroupUpdateOne) RemoveWordListIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.RemoveWordListIDs(ids...)
	return _u
}

// RemoveWordLists removes "word_lists" edges to WordList entities.
func (_u *GroupUpdateOne) RemoveWordLists(v ...*WordList) *GroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWordListIDs(ids...)
}

// ClearCompetitions clears all "competitions" edges to the Competition entity.
func (_u *GroupUpdateOne) ClearCompetitions() *GroupUpdateOne {
	_u.mutation.ClearCompetitions()
	return _u
}

// RemoveCompetitionIDs removes the "competitions" edge to Competition entities by IDs.
func (_u *GroupUpdateOne) RemoveCompetitionIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.RemoveCompetitionIDs(ids...)
	return _u
}

// RemoveCompetitions removes "competitions" edges to Competition entities.
func (_u *GroupUpdateOne) RemoveCompetitions(v ...*Competition) *GroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCompetitionIDs(ids...)
}

// Where appends a list predicates to the GroupUpdate builder.
func (_u *GroupUpdateOne) Where(ps ...predicate.Group) *GroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroupUpdateOne) Select(field string, fields ...string) *GroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Group entity.
func (_u *GroupUpdateOne) Save(ctx context.Context) (*Group, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupUpdateOne) SaveX(ctx context.Context) *Group {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupUpdateOne) check() error {
	if v, ok := _u.mutation.JoinCode(); ok {
		if err := group.JoinCodeValidator(v); err != nil {
			return &ValidationError{Name: "join_code", err: fmt.Errorf(`ent: validator failed for field "Group.join_code": %w`, err)}
		}
	}
	if _u.mutation.SchoolCleared() && len(_u.mutation.SchoolIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Group.school"`)
	}
	return nil
}

func (_u *GroupUpdateOne) sqlSave(ctx context.Context) (_node *Group, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(group.Table, group.Columns, sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Group.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, group.FieldID)
		for _, f := range fields {
			if !group.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != group.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(group.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.JoinCode(); ok {
		_spec.SetField(group.FieldJoinCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.JoinCodeValidUntilTimestamp(); ok {
		_spec.SetField(group.FieldJoinCodeValidUntilTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastUpdatedAtTimestamp(); ok {
		_spec.SetField(group.FieldLastUpdatedAtTimestamp, field.TypeTime, value)
	}
	if _u.mutation.SchoolCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   group.SchoolTable,
			Columns: []string{group.SchoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(school.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SchoolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   group.SchoolTable,
			Columns: []string{group.SchoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(school.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   group.UsersTable,
			Columns: group.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   group.UsersTable,
			Columns: group.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   group.UsersTable,
			Columns: group.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WordListsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.WordListsTable,
			Columns: group.WordListsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWordListsIDs(); len(nodes) > 0 && !_u.mutation.WordListsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.WordListsTable,
			Columns: group.WordListsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WordListsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.WordListsTable,
			Columns: group.WordListsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CompetitionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.CompetitionsTable,
			Columns: group.CompetitionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(competition.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCompetitionsIDs(); len(nodes) > 0 && !_u.mutation.CompetitionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.CompetitionsTable,
			Columns: group.CompetitionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(competition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CompetitionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   group.CompetitionsTable,
			Columns: group.CompetitionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(competition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Group{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{group.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
