// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/PhilAldridge/spell-api/ent/group"
	"github.com/PhilAldridge/spell-api/ent/school"
)

// Group is the model entity for the Group schema.
type Group struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// JoinCode holds the value of the "join_code" field.
	JoinCode string `json:"join_code,omitempty"`
	// JoinCodeValidUntilTimestamp holds the value of the "join_code_valid_until_timestamp" field.
	JoinCodeValidUntilTimestamp time.Time `json:"join_code_valid_until_timestamp,omitempty"`
	// LastUpdatedAtTimestamp holds the value of the "last_updated_at_timestamp" field.
	LastUpdatedAtTimestamp time.Time `json:"last_updated_at_timestamp,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GroupQuery when eager-loading is set.
	Edges         GroupEdges `json:"edges"`
	school_groups *int
	selectValues  sql.SelectValues
}

// GroupEdges holds the relations/edges for other nodes in the graph.
type GroupEdges struct {
	// School holds the value of the school edge.
	School *School `json:"school,omitempty"`
	// Users holds the value of the users edge.
	Users []*User `json:"users,omitempty"`
	// WordLists holds the value of the word_lists edge.
	WordLists []*WordList `json:"word_lists,omitempty"`
	// Competitions holds the value of the competitions edge.
	Competitions []*Competition `json:"competitions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// SchoolOrErr returns the School value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupEdges) SchoolOrErr() (*School, error) {
	if e.School != nil {
		return e.School, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: school.Label}
	}
	return nil, &NotLoadedError{edge: "school"}
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) UsersOrErr() ([]*User, error) {
	if e.loadedTypes[1] {
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// WordListsOrErr returns the WordLists value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) WordListsOrErr() ([]*WordList, error) {
	if e.loadedTypes[2] {
		return e.WordLists, nil
	}
	return nil, &NotLoadedError{edge: "word_lists"}
}

// CompetitionsOrErr returns the Competitions value or an error if the edge
// was not loaded in eager-loading.
func (e GroupEdges) CompetitionsOrErr() ([]*Competition, error) {
	if e.loadedTypes[3] {
		return e.Competitions, nil
	}
	return nil, &NotLoadedError{edge: "competitions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Group) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case group.FieldID:
			values[i] = new(sql.NullInt64)
		case group.FieldName, group.FieldJoinCode:
			values[i] = new(sql.NullString)
		case group.FieldJoinCodeValidUntilTimestamp, group.FieldLastUpdatedAtTimestamp:
			values[i] = new(sql.NullTime)
		case group.ForeignKeys[0]: // school_groups
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Group fields.
func (_m *Group) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case group.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case group.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case group.FieldJoinCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field join_code", values[i])
			} else if value.Valid {
				_m.JoinCode = value.String
			}
		case group.FieldJoinCodeValidUntilTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field join_code_valid_until_timestamp", values[i])
			} else if value.Valid {
				_m.JoinCodeValidUntilTimestamp = value.Time
			}
		case group.FieldLastUpdatedAtTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_updated_at_timestamp", values[i])
			} else if value.Valid {
				_m.LastUpdatedAtTimestamp = value.Time
			}
		case group.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field school_groups", value)
			} else if value.Valid {
				_m.school_groups = new(int)
				*_m.school_groups = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Group.
// This includes values selected through modifiers, order, etc.
func (_m *Group) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySchool queries the "school" edge of the Group entity.
func (_m *Group) QuerySchool() *SchoolQuery {
	return NewGroupClient(_m.config).QuerySchool(_m)
}

// QueryUsers queries the "users" edge of the Group entity.
func (_m *Group) QueryUsers() *UserQuery {
	return NewGroupClient(_m.config).QueryUsers(_m)
}

// QueryWordLists queries the "word_lists" edge of the Group entity.
func (_m *Group) QueryWordLists() *WordListQuery {
	return NewGroupClient(_m.config).QueryWordLists(_m)
}

// QueryCompetitions queries the "competitions" edge of the Group entity.
func (_m *Group) QueryCompetitions() *CompetitionQuery {
	return NewGroupClient(_m.config).QueryCompetitions(_m)
}

// Update returns a builder for updating this Group.
// Note that you need to call Group.Unwrap() before calling this method if this Group
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Group) Update() *GroupUpdateOne {
	return NewGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Group entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Group) Unwrap() *Group {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Group is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Group) String() string {
	var builder strings.Builder
	builder.WriteString("Group(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("join_code=")
	builder.WriteString(_m.JoinCode)
	builder.WriteString(", ")
	builder.WriteString("join_code_valid_until_timestamp=")
	builder.WriteString(_m.JoinCodeValidUntilTimestamp.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_updated_at_timestamp=")
	builder.WriteString(_m.LastUpdatedAtTimestamp.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Groups is a parsable slice of Group.
type Groups []*Group
