// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/PhilAldridge/spell-api/ent/competition"
	"github.com/PhilAldridge/spell-api/ent/group"
	"github.com/PhilAldridge/spell-api/ent/refreshtoken"
	"github.com/PhilAldridge/spell-api/ent/result"
	"github.com/PhilAldridge/spell-api/ent/schema"
	"github.com/PhilAldridge/spell-api/ent/school"
	"github.com/PhilAldridge/spell-api/ent/user"
	"github.com/PhilAldridge/spell-api/ent/word"
	"github.com/PhilAldridge/spell-api/ent/wordlist"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	competitionFields := schema.Competition{}.Fields()
	_ = competitionFields
	// competitionDescName is the schema descriptor for name field.
	competitionDescName := competitionFields[0].Descriptor()
	// competition.NameValidator is a validator for the "name" field. It is called by the builders before save.
	competition.NameValidator = competitionDescName.Validators[0].(func(string) error)
	// competitionDescType is the schema descriptor for type field.
	competitionDescType := competitionFields[1].Descriptor()
	// competition.DefaultType holds the default value on creation for the type field.
	competition.DefaultType = competitionDescType.Default.(string)
	// competitionDescStartTimestamp is the schema descriptor for start_timestamp field.
	competitionDescStartTimestamp := competitionFields[2].Descriptor()
	// competition.DefaultStartTimestamp holds the default value on creation for the start_timestamp field.
	competition.DefaultStartTimestamp = competitionDescStartTimestamp.Default.(time.Time)
	// competitionDescEndTimestamp is the schema descriptor for end_timestamp field.
	competitionDescEndTimestamp := competitionFields[3].Descriptor()
	// competition.DefaultEndTimestamp holds the default value on creation for the end_timestamp field.
	competition.DefaultEndTimestamp = competitionDescEndTimestamp.Default.(time.Time)
	// competitionDescLastUpdatedAtTimestamp is the schema descriptor for last_updated_at_timestamp field.
	competitionDescLastUpdatedAtTimestamp := competitionFields[4].Descriptor()
	// competition.DefaultLastUpdatedAtTimestamp holds the default value on creation for the last_updated_at_timestamp field.
	competition.DefaultLastUpdatedAtTimestamp = competitionDescLastUpdatedAtTimestamp.Default.(time.Time)
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescJoinCode is the schema descriptor for join_code field.
	groupDescJoinCode := groupFields[1].Descriptor()
	// group.JoinCodeValidator is a validator for the "join_code" field. It is called by the builders before save.
	group.JoinCodeValidator = func() func(string) error {
		validators := groupDescJoinCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(join_code string) error {
			for _, fn := range fns {
				if err := fn(join_code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// groupDescJoinCodeValidUntilTimestamp is the schema descriptor for join_code_valid_until_timestamp field.
	groupDescJoinCodeValidUntilTimestamp := groupFields[2].Descriptor()
	// group.DefaultJoinCodeValidUntilTimestamp holds the default value on creation for the join_code_valid_until_timestamp field.
	group.DefaultJoinCodeValidUntilTimestamp = groupDescJoinCodeValidUntilTimestamp.Default.(time.Time)
	// groupDescLastUpdatedAtTimestamp is the schema descriptor for last_updated_at_timestamp field.
	groupDescLastUpdatedAtTimestamp := groupFields[3].Descriptor()
	// group.DefaultLastUpdatedAtTimestamp holds the default value on creation for the last_updated_at_timestamp field.
	group.DefaultLastUpdatedAtTimestamp = groupDescLastUpdatedAtTimestamp.Default.(time.Time)
	refreshtokenFields := schema.RefreshToken{}.Fields()
	_ = refreshtokenFields
	// refreshtokenDescTokenHash is the schema descriptor for token_hash field.
	refreshtokenDescTokenHash := refreshtokenFields[0].Descriptor()
	// refreshtoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	refreshtoken.TokenHashValidator = refreshtokenDescTokenHash.Validators[0].(func(string) error)
	// refreshtokenDescRevoked is the schema descriptor for revoked field.
	refreshtokenDescRevoked := refreshtokenFields[2].Descriptor()
	// refreshtoken.DefaultRevoked holds the default value on creation for the revoked field.
	refreshtoken.DefaultRevoked = refreshtokenDescRevoked.Default.(bool)
	// refreshtokenDescCreatedAt is the schema descriptor for created_at field.
	refreshtokenDescCreatedAt := refreshtokenFields[3].Descriptor()
	// refreshtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	refreshtoken.DefaultCreatedAt = refreshtokenDescCreatedAt.Default.(time.Time)
	resultFields := schema.Result{}.Fields()
	_ = resultFields
	// resultDescType is the schema descriptor for type field.
	resultDescType := resultFields[0].Descriptor()
	// result.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	result.TypeValidator = resultDescType.Validators[0].(func(string) error)
	// resultDescCorrect is the schema descriptor for correct field.
	resultDescCorrect := resultFields[1].Descriptor()
	// result.DefaultCorrect holds the default value on creation for the correct field.
	result.DefaultCorrect = resultDescCorrect.Default.(bool)
	// resultDescTimeTakenInSeconds is the schema descriptor for time_taken_in_seconds field.
	resultDescTimeTakenInSeconds := resultFields[2].Descriptor()
	// result.TimeTakenInSecondsValidator is a validator for the "time_taken_in_seconds" field. It is called by the builders before save.
	result.TimeTakenInSecondsValidator = resultDescTimeTakenInSeconds.Validators[0].(func(float64) error)
	// resultDescTestedAtTimestamp is the schema descriptor for tested_at_timestamp field.
	resultDescTestedAtTimestamp := resultFields[3].Descriptor()
	// result.DefaultTestedAtTimestamp holds the default value on creation for the tested_at_timestamp field.
	result.DefaultTestedAtTimestamp = resultDescTestedAtTimestamp.Default.(time.Time)
	schoolFields := schema.School{}.Fields()
	_ = schoolFields
	// schoolDescJoinCode is the schema descriptor for join_code field.
	schoolDescJoinCode := schoolFields[1].Descriptor()
	// school.JoinCodeValidator is a validator for the "join_code" field. It is called by the builders before save.
	school.JoinCodeValidator = func() func(string) error {
		validators := schoolDescJoinCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(join_code string) error {
			for _, fn := range fns {
				if err := fn(join_code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// schoolDescJoinCodeValidUntilTimestamp is the schema descriptor for join_code_valid_until_timestamp field.
	schoolDescJoinCodeValidUntilTimestamp := schoolFields[2].Descriptor()
	// school.DefaultJoinCodeValidUntilTimestamp holds the default value on creation for the join_code_valid_until_timestamp field.
	school.DefaultJoinCodeValidUntilTimestamp = schoolDescJoinCodeValidUntilTimestamp.Default.(time.Time)
	// schoolDescLastUpdatedAt is the schema descriptor for last_updated_at field.
	schoolDescLastUpdatedAt := schoolFields[3].Descriptor()
	// school.DefaultLastUpdatedAt holds the default value on creation for the last_updated_at field.
	school.DefaultLastUpdatedAt = schoolDescLastUpdatedAt.Default.(time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	wordFields := schema.Word{}.Fields()
	_ = wordFields
	// wordDescName is the schema descriptor for name field.
	wordDescName := wordFields[0].Descriptor()
	// word.NameValidator is a validator for the "name" field. It is called by the builders before save.
	word.NameValidator = wordDescName.Validators[0].(func(string) error)
	// wordDescLastUpdatedAt is the schema descriptor for last_updated_at field.
	wordDescLastUpdatedAt := wordFields[1].Descriptor()
	// word.DefaultLastUpdatedAt holds the default value on creation for the last_updated_at field.
	word.DefaultLastUpdatedAt = wordDescLastUpdatedAt.Default.(time.Time)
	wordlistFields := schema.WordList{}.Fields()
	_ = wordlistFields
	// wordlistDescName is the schema descriptor for name field.
	wordlistDescName := wordlistFields[0].Descriptor()
	// wordlist.NameValidator is a validator for the "name" field. It is called by the builders before save.
	wordlist.NameValidator = wordlistDescName.Validators[0].(func(string) error)
	// wordlistDescLastUpdatedAt is the schema descriptor for last_updated_at field.
	wordlistDescLastUpdatedAt := wordlistFields[1].Descriptor()
	// wordlist.DefaultLastUpdatedAt holds the default value on creation for the last_updated_at field.
	wordlist.DefaultLastUpdatedAt = wordlistDescLastUpdatedAt.Default.(time.Time)
}
