// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PhilAldridge/spell-api/ent/group"
	"github.com/PhilAldridge/spell-api/ent/predicate"
	"github.com/PhilAldridge/spell-api/ent/school"
	"github.com/PhilAldridge/spell-api/ent/user"
	"github.com/PhilAldridge/spell-api/ent/word"
	"github.com/PhilAldridge/spell-api/ent/wordlist"
)

// SchoolUpdate is the builder for updating School entities.
type SchoolUpdate struct {
	config
	hooks    []Hook
	mutation *SchoolMutation
}

// Where appends a list predicates to the SchoolUpdate builder.
func (_u *SchoolUpdate) Where(ps ...predicate.School) *SchoolUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *SchoolUpdate) SetName(v string) *SchoolUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SchoolUpdate) SetNillableName(v *string) *SchoolUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetJoinCode sets the "join_code" field.
func (_u *SchoolUpdate) SetJoinCode(v string) *SchoolUpdate {
	_u.mutation.SetJoinCode(v)
	return _u
}

// SetNillableJoinCode sets the "join_code" field if the given value is not nil.
func (_u *SchoolUpdate) SetNillableJoinCode(v *string) *SchoolUpdate {
	if v != nil {
		_u.SetJoinCode(*v)
	}
	return _u
}

// SetJoinCodeValidUntilTimestamp sets the "join_code_valid_until_timestamp" field.
func (_u *SchoolUpdate) SetJoinCodeValidUntilTimestamp(v time.Time) *SchoolUpdate {
	_u.mutation.SetJoinCodeValidUntilTimestamp(v)
	return _u
}

// SetNillableJoinCodeValidUntilTimestamp sets the "join_code_valid_until_timestamp" field if the given value is not nil.
func (_u *SchoolUpdate) SetNillableJoinCodeValidUntilTimestamp(v *time.Time) *SchoolUpdate {
	if v != nil {
		_u.SetJoinCodeValidUntilTimestamp(*v)
	}
	return _u
}

// SetLastUpdatedAt sets the "last_updated_at" field.
func (_u *SchoolUpdate) SetLastUpdatedAt(v time.Time) *SchoolUpdate {
	_u.mutation.SetLastUpdatedAt(v)
	return _u
}

// SetNillableLastUpdatedAt sets the "last_updated_at" field if the given value is not nil.
func (_u *SchoolUpdate) SetNillableLastUpdatedAt(v *time.Time) *SchoolUpdate {
	if v != nil {
		_u.SetLastUpdatedAt(*v)
	}
	return _u
}

// AddAdminIDs adds the "admins" edge to the User entity by IDs.
func (_u *SchoolUpdate) AddAdminIDs(ids ...int) *SchoolUpdate {
	_u.mutation.AddAdminIDs(ids...)
	return _u
}

// AddAdmins adds the "admins" edges to the User entity.
func (_u *SchoolUpdate) AddAdmins(v ...*User) *SchoolUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAdminIDs(ids...)
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *SchoolUpdate) SetOwnerID(id int) *SchoolUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_u *SchoolUpdate) SetNillableOwnerID(id *int) *SchoolUpdate {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *SchoolUpdate) SetOwner(v *User) *SchoolUpdate {
	return _u.SetOwnerID(v.ID)
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_u *SchoolUpdate) AddGroupIDs(ids ...int) *SchoolUpdate {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the Group entity.
func (_u *SchoolUpdate) AddGroups(v ...*Group) *SchoolUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// AddCustomWordIDs adds the "custom_words" edge to the Word entity by IDs.
func (_u *SchoolUpdate) AddCustomWordIDs(ids ...int) *SchoolUpdate {
	_u.mutation.AddCustomWordIDs(ids...)
	return _u
}

// AddCustomWords adds the "custom_words" edges to the Word entity.
func (_u *SchoolUpdate) AddCustomWords(v ...*Word) *SchoolUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCustomWordIDs(ids...)
}

// AddCustomWordListIDs adds the "custom_word_lists" edge to the WordList entity by IDs.
func (_u *SchoolUpdate) AddCustomWordListIDs(ids ...int) *SchoolUpdate {
	_u.mutation.AddCustomWordListIDs(ids...)
	return _u
}

// AddCustomWordLists adds the "custom_word_lists" edges to the WordList entity.
func (_u *SchoolUpdate) AddCustomWordLists(v ...*WordList) *SchoolUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCustomWordListIDs(ids...)
}

// Mutation returns the SchoolMutation object of the builder.
func (_u *SchoolUpdate) Mutation() *SchoolMutation {
	return _u.mutation
}

// ClearAdmins clears all "admins" edges to the User entity.
func (_u *SchoolUpdate) ClearAdmins() *SchoolUpdate {
	_u.mutation.ClearAdmins()
	return _u
}

// RemoveAdminIDs removes the "admins" edge to User entities by IDs.
func (_u *SchoolUpdate) RemoveAdminIDs(ids ...int) *SchoolUpdate {
	_u.mutation.RemoveAdminIDs(ids...)
	return _u
}

// RemoveAdmins removes "admins" edges to User entities.
func (_u *SchoolUpdate) RemoveAdmins(v ...*User) *SchoolUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAdminIDs(ids...)
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *SchoolUpdate) ClearOwner() *SchoolUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearGroups clears all "groups" edges to the Group entity.
func (_u *SchoolUpdate) ClearGroups() *SchoolUpdate {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (_u *SchoolUpdate) RemoveGroupIDs(ids ...int) *SchoolUpdate {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to Group entities.
func (_u *SchoolUpdate) RemoveGroups(v ...*Group) *SchoolUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearCustomWords clears all "custom_words" edges to the Word entity.
func (_u *SchoolUpdate) ClearCustomWords() *SchoolUpdate {
	_u.mutation.ClearCustomWords()
	return _u
}

// RemoveCustomWordIDs removes the "custom_words" edge to Word entities by IDs.
func (_u *SchoolUpdate) RemoveCustomWordIDs(ids ...int) *SchoolUpdate {
	_u.mutation.RemoveCustomWordIDs(ids...)
	return _u
}

// RemoveCustomWords removes "custom_words" edges to Word entities.
func (_u *SchoolUpdate) RemoveCustomWords(v ...*Word) *SchoolUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCustomWordIDs(ids...)
}

// ClearCustomWordLists clears all "custom_word_lists" edges to the WordList entity.
func (_u *SchoolUpdate) ClearCustomWordLists() *SchoolUpdate {
	_u.mutation.ClearCustomWordLists()
	return _u
}

// RemoveCustomWordListIDs removes the "custom_word_lists" edge to WordList entities by IDs.
func (_u *SchoolUpdate) RemoveCustomWordListIDs(ids ...int) *SchoolUpdate {
	_u.mutation.RemoveCustomWordListIDs(ids...)
	return _u
}

// RemoveCustomWordLists removes "custom_word_lists" edges to WordList entities.
func (_u *SchoolUpdate) RemoveCustomWordLists(v ...*WordList) *SchoolUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCustomWordListIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SchoolUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SchoolUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SchoolUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SchoolUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SchoolUpdate) check() error {
	if v, ok := _u.mutation.JoinCode(); ok {
		if err := school.JoinCodeValidator(v); err != nil {
			return &ValidationError{Name: "join_code", err: fmt.Errorf(`ent: validator failed for field "School.join_code": %w`, err)}
		}
	}
	return nil
}

func (_u *SchoolUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(school.Table, school.Columns, sqlgraph.NewFieldSpec(school.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(school.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.JoinCode(); ok {
		_spec.SetField(school.FieldJoinCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.JoinCodeValidUntilTimestamp(); ok {
		_spec.SetField(school.FieldJoinCodeValidUntilTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastUpdatedAt(); ok {
		_spec.SetField(school.FieldLastUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   school.AdminsTable,
			Columns: school.AdminsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAdminsIDs(); len(nodes) > 0 && !_u.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   school.AdminsTable,
			Columns: school.AdminsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   school.AdminsTable,
			Columns: school.AdminsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   school.OwnerTable,
			Columns: []string{school.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   school.OwnerTable,
			Columns: []string{school.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.GroupsTable,
			Columns: []string{school.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.GroupsTable,
			Columns: []string{school.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.GroupsTable,
			Columns: []string{school.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CustomWordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.CustomWordsTable,
			Columns: []string{school.CustomWordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(word.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCustomWordsIDs(); len(nodes) > 0 && !_u.mutation.CustomWordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.CustomWordsTable,
			Columns: []string{school.CustomWordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(word.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomWordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.CustomWordsTable,
			Columns: []string{school.CustomWordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(word.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CustomWordListsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.CustomWordListsTable,
			Columns: []string{school.CustomWordListsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCustomWordListsIDs(); len(nodes) > 0 && !_u.mutation.CustomWordListsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.CustomWordListsTable,
			Columns: []string{school.CustomWordListsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomWordListsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.CustomWordListsTable,
			Columns: []string{school.CustomWordListsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{school.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SchoolUpdateOne is the builder for updating a single School entity.
type SchoolUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SchoolMutation
}

// SetName sets the "name" field.
func (_u *SchoolUpdateOne) SetName(v string) *SchoolUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SchoolUpdateOne) SetNillableName(v *string) *SchoolUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetJoinCode sets the "join_code" field.
func (_u *SchoolUpdateOne) SetJoinCode(v string) *SchoolUpdateOne {
	_u.mutation.SetJoinCode(v)
	return _u
}

// SetNillableJoinCode sets the "join_code" field if the given value is not nil.
func (_u *SchoolUpdateOne) SetNillableJoinCode(v *string) *SchoolUpdateOne {
	if v != nil {
		_u.SetJoinCode(*v)
	}
	return _u
}

// SetJoinCodeValidUntilTimestamp sets the "join_code_valid_until_timestamp" field.
func (_u *SchoolUpdateOne) SetJoinCodeValidUntilTimestamp(v time.Time) *SchoolUpdateOne {
	_u.mutation.SetJoinCodeValidUntilTimestamp(v)
	return _u
}

// SetNillableJoinCodeValidUntilTimestamp sets the "join_code_valid_until_timestamp" field if the given value is not nil.
func (_u *SchoolUpdateOne) SetNillableJoinCodeValidUntilTimestamp(v *time.Time) *SchoolUpdateOne {
	if v != nil {
		_u.SetJoinCodeValidUntilTimestamp(*v)
	}
	return _u
}

// SetLastUpdatedAt sets the "last_updated_at" field.
func (_u *SchoolUpdateOne) SetLastUpdatedAt(v time.Time) *SchoolUpdateOne {
	_u.mutation.SetLastUpdatedAt(v)
	return _u
}

// SetNillableLastUpdatedAt sets the "last_updated_at" field if the given value is not nil.
func (_u *SchoolUpdateOne) SetNillableLastUpdatedAt(v *time.Time) *SchoolUpdateOne {
	if v != nil {
		_u.SetLastUpdatedAt(*v)
	}
	return _u
}

// AddAdminIDs adds the "admins" edge to the User entity by IDs.
func (_u *SchoolUpdateOne) AddAdminIDs(ids ...int) *SchoolUpdateOne {
	_u.mutation.AddAdminIDs(ids...)
	return _u
}

// AddAdmins adds the "admins" edges to the User entity.
func (_u *SchoolUpdateOne) AddAdmins(v ...*User) *SchoolUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAdminIDs(ids...)
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *SchoolUpdateOne) SetOwnerID(id int) *SchoolUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_u *SchoolUpdateOne) SetNillableOwnerID(id *int) *SchoolUpdateOne {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *SchoolUpdateOne) SetOwner(v *User) *SchoolUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_u *SchoolUpdateOne) AddGroupIDs(ids ...int) *SchoolUpdateOne {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the Group entity.
func (_u *SchoolUpdateOne) AddGroups(v ...*Group) *SchoolUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// AddCustomWordIDs adds the "custom_words" edge to the Word entity by IDs.
func (_u *SchoolUpdateOne) AddCustomWordIDs(ids ...int) *SchoolUpdateOne {
	_u.mutation.AddCustomWordIDs(ids...)
	return _u
}

// AddCustomWords adds the "custom_words" edges to the Word entity.
func (_u *SchoolUpdateOne) AddCustomWords(v ...*Word) *SchoolUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCustomWordIDs(ids...)
}

// AddCustomWordListIDs adds the "custom_word_lists" edge to the WordList entity by IDs.
func (_u *SchoolUpdateOne) AddCustomWordListIDs(ids ...int) *SchoolUpdateOne {
	_u.mutation.AddCustomWordListIDs(ids...)
	return _u
}

// AddCustomWordLists adds the "custom_word_lists" edges to the WordList entity.
func (_u *SchoolUpdateOne) AddCustomWordLists(v ...*WordList) *SchoolUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCustomWordListIDs(ids...)
}

// Mutation returns the SchoolMutation object of the builder.
func (_u *SchoolUpdateOne) Mutation() *SchoolMutation {
	return _u.mutation
}

// ClearAdmins clears all "admins" edges to the User entity.
func (_u *SchoolUpdateOne) ClearAdmins() *SchoolUpdateOne {
	_u.mutation.ClearAdmins()
	return _u
}

// RemoveAdminIDs removes the "admins" edge to User entities by IDs.
func (_u *SchoolUpdateOne) RemoveAdminIDs(ids ...int) *SchoolUpdateOne {
	_u.mutation.RemoveAdminIDs(ids...)
	return _u
}

// RemoveAdmins removes "admins" edges to User entities.
func (_u *SchoolUpdateOne) RemoveAdmins(v ...*User) *SchoolUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAdminIDs(ids...)
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *SchoolUpdateOne) ClearOwner() *SchoolUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearGroups clears all "groups" edges to the Group entity.
func (_u *SchoolUpdateOne) ClearGroups() *SchoolUpdateOne {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (_u *SchoolUpdateOne) RemoveGroupIDs(ids ...int) *SchoolUpdateOne {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to Group entities.
func (_u *SchoolUpdateOne) RemoveGroups(v ...*Group) *SchoolUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearCustomWords clears all "custom_words" edges to the Word entity.
func (_u *SchoolUpdateOne) ClearCustomWords() *SchoolUpdateOne {
	_u.mutation.ClearCustomWords()
	return _u
}

// RemoveCustomWordIDs removes the "custom_words" edge to Word entities by IDs.
func (_u *SchoolUpdateOne) RemoveCustomWordIDs(ids ...int) *SchoolUpdateOne {
	_u.mutation.RemoveCustomWordIDs(ids...)
	return _u
}

// RemoveCustomWords removes "custom_words" edges to Word entities.
func (_u *SchoolUpdateOne) RemoveCustomWords(v ...*Word) *SchoolUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCustomWordIDs(ids...)
}

// ClearCustomWordLists clears all "custom_word_lists" edges to the WordList entity.
func (_u *SchoolUpdateOne) ClearCustomWordLists() *SchoolUpdateOne {
	_u.mutation.ClearCustomWordLists()
	return _u
}

// RemoveCustomWordListIDs removes the "custom_word_lists" edge to WordList entities by IDs.
func (_u *SchoolUpdateOne) RemoveCustomWordListIDs(ids ...int) *SchoolUpdateOne {
	_u.mutation.RemoveCustomWordListIDs(ids...)
	return _u
}

// RemoveCustomWordLists removes "custom_word_lists" edges to WordList entities.
func (_u *SchoolUpdateOne) RemoveCustomWordLists(v ...*WordList) *SchoolUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCustomWordListIDs(ids...)
}

// Where appends a list predicates to the SchoolUpdate builder.
func (_u *SchoolUpdateOne) Where(ps ...predicate.School) *SchoolUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SchoolUpdateOne) Select(field string, fields ...string) *SchoolUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated School entity.
func (_u *SchoolUpdateOne) Save(ctx context.Context) (*School, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SchoolUpdateOne) SaveX(ctx context.Context) *School {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SchoolUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SchoolUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SchoolUpdateOne) check() error {
	if v, ok := _u.mutation.JoinCode(); ok {
		if err := school.JoinCodeValidator(v); err != nil {
			return &ValidationError{Name: "join_code", err: fmt.Errorf(`ent: validator failed for field "School.join_code": %w`, err)}
		}
	}
	return nil
}

func (_u *SchoolUpdateOne) sqlSave(ctx context.Context) (_node *School, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(school.Table, school.Columns, sqlgraph.NewFieldSpec(school.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "School.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, school.FieldID)
		for _, f := range fields {
			if !school.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != school.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(school.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.JoinCode(); ok {
		_spec.SetField(school.FieldJoinCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.JoinCodeValidUntilTimestamp(); ok {
		_spec.SetField(school.FieldJoinCodeValidUntilTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastUpdatedAt(); ok {
		_spec.SetField(school.FieldLastUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   school.AdminsTable,
			Columns: school.AdminsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAdminsIDs(); len(nodes) > 0 && !_u.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   school.AdminsTable,
			Columns: school.AdminsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   school.AdminsTable,
			Columns: school.AdminsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   school.OwnerTable,
			Columns: []string{school.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   school.OwnerTable,
			Columns: []string{school.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.GroupsTable,
			Columns: []string{school.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.GroupsTable,
			Columns: []string{school.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.GroupsTable,
			Columns: []string{school.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CustomWordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.CustomWordsTable,
			Columns: []string{school.CustomWordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(word.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCustomWordsIDs(); len(nodes) > 0 && !_u.mutation.CustomWordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.CustomWordsTable,
			Columns: []string{school.CustomWordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(word.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomWordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.CustomWordsTable,
			Columns: []string{school.CustomWordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(word.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CustomWordListsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.CustomWordListsTable,
			Columns: []string{school.CustomWordListsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCustomWordListsIDs(); len(nodes) > 0 && !_u.mutation.CustomWordListsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.CustomWordListsTable,
			Columns: []string{school.CustomWordListsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomWordListsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   school.CustomWordListsTable,
			Columns: []string{school.CustomWordListsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &School{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{school.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
