// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/PhilAldridge/spell-api/ent/school"
	"github.com/PhilAldridge/spell-api/ent/user"
)

// School is the model entity for the School schema.
type School struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// LastUpdatedAt holds the value of the "last_updated_at" field.
	LastUpdatedAt time.Time `json:"last_updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SchoolQuery when eager-loading is set.
	Edges             SchoolEdges `json:"edges"`
	user_owned_school *int
	selectValues      sql.SelectValues
}

// SchoolEdges holds the relations/edges for other nodes in the graph.
type SchoolEdges struct {
	// Admins holds the value of the admins edge.
	Admins []*User `json:"admins,omitempty"`
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// Groups holds the value of the groups edge.
	Groups []*Group `json:"groups,omitempty"`
	// CustomWords holds the value of the custom_words edge.
	CustomWords []*Word `json:"custom_words,omitempty"`
	// CustomWordLists holds the value of the custom_word_lists edge.
	CustomWordLists []*WordList `json:"custom_word_lists,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// AdminsOrErr returns the Admins value or an error if the edge
// was not loaded in eager-loading.
func (e SchoolEdges) AdminsOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.Admins, nil
	}
	return nil, &NotLoadedError{edge: "admins"}
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SchoolEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// GroupsOrErr returns the Groups value or an error if the edge
// was not loaded in eager-loading.
func (e SchoolEdges) GroupsOrErr() ([]*Group, error) {
	if e.loadedTypes[2] {
		return e.Groups, nil
	}
	return nil, &NotLoadedError{edge: "groups"}
}

// CustomWordsOrErr returns the CustomWords value or an error if the edge
// was not loaded in eager-loading.
func (e SchoolEdges) CustomWordsOrErr() ([]*Word, error) {
	if e.loadedTypes[3] {
		return e.CustomWords, nil
	}
	return nil, &NotLoadedError{edge: "custom_words"}
}

// CustomWordListsOrErr returns the CustomWordLists value or an error if the edge
// was not loaded in eager-loading.
func (e SchoolEdges) CustomWordListsOrErr() ([]*WordList, error) {
	if e.loadedTypes[4] {
		return e.CustomWordLists, nil
	}
	return nil, &NotLoadedError{edge: "custom_word_lists"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*School) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case school.FieldID:
			values[i] = new(sql.NullInt64)
		case school.FieldName:
			values[i] = new(sql.NullString)
		case school.FieldLastUpdatedAt:
			values[i] = new(sql.NullTime)
		case school.ForeignKeys[0]: // user_owned_school
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the School fields.
func (_m *School) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case school.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case school.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case school.FieldLastUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_updated_at", values[i])
			} else if value.Valid {
				_m.LastUpdatedAt = value.Time
			}
		case school.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_owned_school", value)
			} else if value.Valid {
				_m.user_owned_school = new(int)
				*_m.user_owned_school = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the School.
// This includes values selected through modifiers, order, etc.
func (_m *School) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAdmins queries the "admins" edge of the School entity.
func (_m *School) QueryAdmins() *UserQuery {
	return NewSchoolClient(_m.config).QueryAdmins(_m)
}

// QueryOwner queries the "owner" edge of the School entity.
func (_m *School) QueryOwner() *UserQuery {
	return NewSchoolClient(_m.config).QueryOwner(_m)
}

// QueryGroups queries the "groups" edge of the School entity.
func (_m *School) QueryGroups() *GroupQuery {
	return NewSchoolClient(_m.config).QueryGroups(_m)
}

// QueryCustomWords queries the "custom_words" edge of the School entity.
func (_m *School) QueryCustomWords() *WordQuery {
	return NewSchoolClient(_m.config).QueryCustomWords(_m)
}

// QueryCustomWordLists queries the "custom_word_lists" edge of the School entity.
func (_m *School) QueryCustomWordLists() *WordListQuery {
	return NewSchoolClient(_m.config).QueryCustomWordLists(_m)
}

// Update returns a builder for updating this School.
// Note that you need to call School.Unwrap() before calling this method if this School
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *School) Update() *SchoolUpdateOne {
	return NewSchoolClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the School entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *School) Unwrap() *School {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: School is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *School) String() string {
	var builder strings.Builder
	builder.WriteString("School(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("last_updated_at=")
	builder.WriteString(_m.LastUpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Schools is a parsable slice of School.
type Schools []*School
