// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PhilAldridge/spell-api/ent/competition"
	"github.com/PhilAldridge/spell-api/ent/group"
	"github.com/PhilAldridge/spell-api/ent/predicate"
	"github.com/PhilAldridge/spell-api/ent/school"
	"github.com/PhilAldridge/spell-api/ent/word"
	"github.com/PhilAldridge/spell-api/ent/wordlist"
)

// WordListQuery is the builder for querying WordList entities.
type WordListQuery struct {
	config
	ctx              *QueryContext
	order            []wordlist.OrderOption
	inters           []Interceptor
	predicates       []predicate.WordList
	withWords        *WordQuery
	withGroups       *GroupQuery
	withSchool       *SchoolQuery
	withCompetitions *CompetitionQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WordListQuery builder.
func (_q *WordListQuery) Where(ps ...predicate.WordList) *WordListQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *WordListQuery) Limit(limit int) *WordListQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *WordListQuery) Offset(offset int) *WordListQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *WordListQuery) Unique(unique bool) *WordListQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *WordListQuery) Order(o ...wordlist.OrderOption) *WordListQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryWords chains the current query on the "words" edge.
func (_q *WordListQuery) QueryWords() *WordQuery {
	query := (&WordClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wordlist.Table, wordlist.FieldID, selector),
			sqlgraph.To(word.Table, word.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, wordlist.WordsTable, wordlist.WordsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroups chains the current query on the "groups" edge.
func (_q *WordListQuery) QueryGroups() *GroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wordlist.Table, wordlist.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, wordlist.GroupsTable, wordlist.GroupsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySchool chains the current query on the "school" edge.
func (_q *WordListQuery) QuerySchool() *SchoolQuery {
	query := (&SchoolClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wordlist.Table, wordlist.FieldID, selector),
			sqlgraph.To(school.Table, school.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, wordlist.SchoolTable, wordlist.SchoolColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCompetitions chains the current query on the "competitions" edge.
func (_q *WordListQuery) QueryCompetitions() *CompetitionQuery {
	query := (&CompetitionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wordlist.Table, wordlist.FieldID, selector),
			sqlgraph.To(competition.Table, competition.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, wordlist.CompetitionsTable, wordlist.CompetitionsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WordList entity from the query.
// Returns a *NotFoundError when no WordList was found.
func (_q *WordListQuery) First(ctx context.Context) (*WordList, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{wordlist.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *WordListQuery) FirstX(ctx context.Context) *WordList {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WordList ID from the query.
// Returns a *NotFoundError when no WordList ID was found.
func (_q *WordListQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{wordlist.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *WordListQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WordList entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WordList entity is found.
// Returns a *NotFoundError when no WordList entities are found.
func (_q *WordListQuery) Only(ctx context.Context) (*WordList, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{wordlist.Label}
	default:
		return nil, &NotSingularError{wordlist.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *WordListQuery) OnlyX(ctx context.Context) *WordList {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WordList ID in the query.
// Returns a *NotSingularError when more than one WordList ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *WordListQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{wordlist.Label}
	default:
		err = &NotSingularError{wordlist.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *WordListQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WordLists.
func (_q *WordListQuery) All(ctx context.Context) ([]*WordList, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WordList, *WordListQuery]()
	return withInterceptors[[]*WordList](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *WordListQuery) AllX(ctx context.Context) []*WordList {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WordList IDs.
func (_q *WordListQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(wordlist.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *WordListQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *WordListQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*WordListQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *WordListQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *WordListQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *WordListQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WordListQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *WordListQuery) Clone() *WordListQuery {
	if _q == nil {
		return nil
	}
	return &WordListQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]wordlist.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.WordList{}, _q.predicates...),
		withWords:        _q.withWords.Clone(),
		withGroups:       _q.withGroups.Clone(),
		withSchool:       _q.withSchool.Clone(),
		withCompetitions: _q.withCompetitions.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithWords tells the query-builder to eager-load the nodes that are connected to
// the "words" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WordListQuery) WithWords(opts ...func(*WordQuery)) *WordListQuery {
	query := (&WordClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWords = query
	return _q
}

// WithGroups tells the query-builder to eager-load the nodes that are connected to
// the "groups" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WordListQuery) WithGroups(opts ...func(*GroupQuery)) *WordListQuery {
	query := (&GroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroups = query
	return _q
}

// WithSchool tells the query-builder to eager-load the nodes that are connected to
// the "school" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WordListQuery) WithSchool(opts ...func(*SchoolQuery)) *WordListQuery {
	query := (&SchoolClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSchool = query
	return _q
}

// WithCompetitions tells the query-builder to eager-load the nodes that are connected to
// the "competitions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WordListQuery) WithCompetitions(opts ...func(*CompetitionQuery)) *WordListQuery {
	query := (&CompetitionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCompetitions = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WordList.Query().
//		GroupBy(wordlist.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *WordListQuery) GroupBy(field string, fields ...string) *WordListGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WordListGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = wordlist.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.WordList.Query().
//		Select(wordlist.FieldName).
//		Scan(ctx, &v)
func (_q *WordListQuery) Select(fields ...string) *WordListSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &WordListSelect{WordListQuery: _q}
	sbuild.label = wordlist.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WordListSelect configured with the given aggregations.
func (_q *WordListQuery) Aggregate(fns ...AggregateFunc) *WordListSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *WordListQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !wordlist.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *WordListQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WordList, error) {
	var (
		nodes       = []*WordList{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withWords != nil,
			_q.withGroups != nil,
			_q.withSchool != nil,
			_q.withCompetitions != nil,
		}
	)
	if _q.withSchool != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, wordlist.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WordList).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WordList{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withWords; query != nil {
		if err := _q.loadWords(ctx, query, nodes,
			func(n *WordList) { n.Edges.Words = []*Word{} },
			func(n *WordList, e *Word) { n.Edges.Words = append(n.Edges.Words, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGroups; query != nil {
		if err := _q.loadGroups(ctx, query, nodes,
			func(n *WordList) { n.Edges.Groups = []*Group{} },
			func(n *WordList, e *Group) { n.Edges.Groups = append(n.Edges.Groups, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSchool; query != nil {
		if err := _q.loadSchool(ctx, query, nodes, nil,
			func(n *WordList, e *School) { n.Edges.School = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCompetitions; query != nil {
		if err := _q.loadCompetitions(ctx, query, nodes,
			func(n *WordList) { n.Edges.Competitions = []*Competition{} },
			func(n *WordList, e *Competition) { n.Edges.Competitions = append(n.Edges.Competitions, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *WordListQuery) loadWords(ctx context.Context, query *WordQuery, nodes []*WordList, init func(*WordList), assign func(*WordList, *Word)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*WordList)
	nids := make(map[int]map[*WordList]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(wordlist.WordsTable)
		s.Join(joinT).On(s.C(word.FieldID), joinT.C(wordlist.WordsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(wordlist.WordsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(wordlist.WordsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*WordList]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Word](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "words" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *WordListQuery) loadGroups(ctx context.Context, query *GroupQuery, nodes []*WordList, init func(*WordList), assign func(*WordList, *Group)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*WordList)
	nids := make(map[int]map[*WordList]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(wordlist.GroupsTable)
		s.Join(joinT).On(s.C(group.FieldID), joinT.C(wordlist.GroupsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(wordlist.GroupsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(wordlist.GroupsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*WordList]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Group](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "groups" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *WordListQuery) loadSchool(ctx context.Context, query *SchoolQuery, nodes []*WordList, init func(*WordList), assign func(*WordList, *School)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*WordList)
	for i := range nodes {
		if nodes[i].school_custom_word_lists == nil {
			continue
		}
		fk := *nodes[i].school_custom_word_lists
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(school.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "school_custom_word_lists" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *WordListQuery) loadCompetitions(ctx context.Context, query *CompetitionQuery, nodes []*WordList, init func(*WordList), assign func(*WordList, *Competition)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*WordList)
	nids := make(map[int]map[*WordList]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(wordlist.CompetitionsTable)
		s.Join(joinT).On(s.C(competition.FieldID), joinT.C(wordlist.CompetitionsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(wordlist.CompetitionsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(wordlist.CompetitionsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*WordList]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Competition](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "competitions" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (_q *WordListQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *WordListQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(wordlist.Table, wordlist.Columns, sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wordlist.FieldID)
		for i := range fields {
			if fields[i] != wordlist.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *WordListQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(wordlist.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = wordlist.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WordListGroupBy is the group-by builder for WordList entities.
type WordListGroupBy struct {
	selector
	build *WordListQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *WordListGroupBy) Aggregate(fns ...AggregateFunc) *WordListGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *WordListGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WordListQuery, *WordListGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *WordListGroupBy) sqlScan(ctx context.Context, root *WordListQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WordListSelect is the builder for selecting fields of WordList entities.
type WordListSelect struct {
	*WordListQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *WordListSelect) Aggregate(fns ...AggregateFunc) *WordListSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *WordListSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WordListQuery, *WordListSelect](ctx, _s.WordListQuery, _s, _s.inters, v)
}

func (_s *WordListSelect) sqlScan(ctx context.Context, root *WordListQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
