// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PhilAldridge/spell-api/ent/competition"
	"github.com/PhilAldridge/spell-api/ent/group"
	"github.com/PhilAldridge/spell-api/ent/predicate"
	"github.com/PhilAldridge/spell-api/ent/word"
	"github.com/PhilAldridge/spell-api/ent/wordlist"
)

// WordListUpdate is the builder for updating WordList entities.
type WordListUpdate struct {
	config
	hooks    []Hook
	mutation *WordListMutation
}

// Where appends a list predicates to the WordListUpdate builder.
func (_u *WordListUpdate) Where(ps ...predicate.WordList) *WordListUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *WordListUpdate) SetName(v string) *WordListUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WordListUpdate) SetNillableName(v *string) *WordListUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLastUpdatedAt sets the "last_updated_at" field.
func (_u *WordListUpdate) SetLastUpdatedAt(v time.Time) *WordListUpdate {
	_u.mutation.SetLastUpdatedAt(v)
	return _u
}

// SetNillableLastUpdatedAt sets the "last_updated_at" field if the given value is not nil.
func (_u *WordListUpdate) SetNillableLastUpdatedAt(v *time.Time) *WordListUpdate {
	if v != nil {
		_u.SetLastUpdatedAt(*v)
	}
	return _u
}

// AddWordIDs adds the "words" edge to the Word entity by IDs.
func (_u *WordListUpdate) AddWordIDs(ids ...int) *WordListUpdate {
	_u.mutation.AddWordIDs(ids...)
	return _u
}

// AddWords adds the "words" edges to the Word entity.
func (_u *WordListUpdate) AddWords(v ...*Word) *WordListUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWordIDs(ids...)
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_u *WordListUpdate) AddGroupIDs(ids ...int) *WordListUpdate {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the Group entity.
func (_u *WordListUpdate) AddGroups(v ...*Group) *WordListUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// AddCompetitionIDs adds the "competitions" edge to the Competition entity by IDs.
func (_u *WordListUpdate) AddCompetitionIDs(ids ...int) *WordListUpdate {
	_u.mutation.AddCompetitionIDs(ids...)
	return _u
}

// AddCompetitions adds the "competitions" edges to the Competition entity.
func (_u *WordListUpdate) AddCompetitions(v ...*Competition) *WordListUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCompetitionIDs(ids...)
}

// Mutation returns the WordListMutation object of the builder.
func (_u *WordListUpdate) Mutation() *WordListMutation {
	return _u.mutation
}

// ClearWords clears all "words" edges to the Word entity.
func (_u *WordListUpdate) ClearWords() *WordListUpdate {
	_u.mutation.ClearWords()
	return _u
}

// RemoveWordIDs removes the "words" edge to Word entities by IDs.
func (_u *WordListUpdate) RemoveWordIDs(ids ...int) *WordListUpdate {
	_u.mutation.RemoveWordIDs(ids...)
	return _u
}

// RemoveWords removes "words" edges to Word entities.
func (_u *WordListUpdate) RemoveWords(v ...*Word) *WordListUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWordIDs(ids...)
}

// ClearGroups clears all "groups" edges to the Group entity.
func (_u *WordListUpdate) ClearGroups() *WordListUpdate {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (_u *WordListUpdate) RemoveGroupIDs(ids ...int) *WordListUpdate {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to Group entities.
func (_u *WordListUpdate) RemoveGroups(v ...*Group) *WordListUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearCompetitions clears all "competitions" edges to the Competition entity.
func (_u *WordListUpdate) ClearCompetitions() *WordListUpdate {
	_u.mutation.ClearCompetitions()
	return _u
}

// RemoveCompetitionIDs removes the "competitions" edge to Competition entities by IDs.
func (_u *WordListUpdate) RemoveCompetitionIDs(ids ...int) *WordListUpdate {
	_u.mutation.RemoveCompetitionIDs(ids...)
	return _u
}

// RemoveCompetitions removes "competitions" edges to Competition entities.
func (_u *WordListUpdate) RemoveCompetitions(v ...*Competition) *WordListUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCompetitionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WordListUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WordListUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WordListUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WordListUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WordListUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := wordlist.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "WordList.name": %w`, err)}
		}
	}
	return nil
}

func (_u *WordListUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wordlist.Table, wordlist.Columns, sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(wordlist.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastUpdatedAt(); ok {
		_spec.SetField(wordlist.FieldLastUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.WordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   wordlist.WordsTable,
			Columns: wordlist.WordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(word.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWordsIDs(); len(nodes) > 0 && !_u.mutation.WordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   wordlist.WordsTable,
			Columns: wordlist.WordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(word.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   wordlist.WordsTable,
			Columns: wordlist.WordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(word.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   wordlist.GroupsTable,
			Columns: wordlist.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   wordlist.GroupsTable,
			Columns: wordlist.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   wordlist.GroupsTable,
			Columns: wordlist.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CompetitionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   wordlist.CompetitionsTable,
			Columns: wordlist.CompetitionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(competition.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCompetitionsIDs(); len(nodes) > 0 && !_u.mutation.CompetitionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   wordlist.CompetitionsTable,
			Columns: wordlist.CompetitionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(competition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CompetitionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   wordlist.CompetitionsTable,
			Columns: wordlist.CompetitionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(competition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wordlist.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WordListUpdateOne is the builder for updating a single WordList entity.
type WordListUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WordListMutation
}

// SetName sets the "name" field.
func (_u *WordListUpdateOne) SetName(v string) *WordListUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WordListUpdateOne) SetNillableName(v *string) *WordListUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLastUpdatedAt sets the "last_updated_at" field.
func (_u *WordListUpdateOne) SetLastUpdatedAt(v time.Time) *WordListUpdateOne {
	_u.mutation.SetLastUpdatedAt(v)
	return _u
}

// SetNillableLastUpdatedAt sets the "last_updated_at" field if the given value is not nil.
func (_u *WordListUpdateOne) SetNillableLastUpdatedAt(v *time.Time) *WordListUpdateOne {
	if v != nil {
		_u.SetLastUpdatedAt(*v)
	}
	return _u
}

// AddWordIDs adds the "words" edge to the Word entity by IDs.
func (_u *WordListUpdateOne) AddWordIDs(ids ...int) *WordListUpdateOne {
	_u.mutation.AddWordIDs(ids...)
	return _u
}

// AddWords adds the "words" edges to the Word entity.
func (_u *WordListUpdateOne) AddWords(v ...*Word) *WordListUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWordIDs(ids...)
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_u *WordListUpdateOne) AddGroupIDs(ids ...int) *WordListUpdateOne {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the Group entity.
func (_u *WordListUpdateOne) AddGroups(v ...*Group) *WordListUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// AddCompetitionIDs adds the "competitions" edge to the Competition entity by IDs.
func (_u *WordListUpdateOne) AddCompetitionIDs(ids ...int) *WordListUpdateOne {
	_u.mutation.AddCompetitionIDs(ids...)
	return _u
}

// AddCompetitions adds the "competitions" edges to the Competition entity.
func (_u *WordListUpdateOne) AddCompetitions(v ...*Competition) *WordListUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCompetitionIDs(ids...)
}

// Mutation returns the WordListMutation object of the builder.
func (_u *WordListUpdateOne) Mutation() *WordListMutation {
	return _u.mutation
}

// ClearWords clears all "words" edges to the Word entity.
func (_u *WordListUpdateOne) ClearWords() *WordListUpdateOne {
	_u.mutation.ClearWords()
	return _u
}

// RemoveWordIDs removes the "words" edge to Word entities by IDs.
func (_u *WordListUpdateOne) RemoveWordIDs(ids ...int) *WordListUpdateOne {
	_u.mutation.RemoveWordIDs(ids...)
	return _u
}

// RemoveWords removes "words" edges to Word entities.
func (_u *WordListUpdateOne) RemoveWords(v ...*Word) *WordListUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWordIDs(ids...)
}

// ClearGroups clears all "groups" edges to the Group entity.
func (_u *WordListUpdateOne) ClearGroups() *WordListUpdateOne {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (_u *WordListUpdateOne) RemoveGroupIDs(ids ...int) *WordListUpdateOne {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to Group entities.
func (_u *WordListUpdateOne) RemoveGroups(v ...*Group) *WordListUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearCompetitions clears all "competitions" edges to the Competition entity.
func (_u *WordListUpdateOne) ClearCompetitions() *WordListUpdateOne {
	_u.mutation.ClearCompetitions()
	return _u
}

// RemoveCompetitionIDs removes the "competitions" edge to Competition entities by IDs.
func (_u *WordListUpdateOne) RemoveCompetitionIDs(ids ...int) *WordListUpdateOne {
	_u.mutation.RemoveCompetitionIDs(ids...)
	return _u
}

// RemoveCompetitions removes "competitions" edges to Competition entities.
func (_u *WordListUpdateOne) RemoveCompetitions(v ...*Competition) *WordListUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCompetitionIDs(ids...)
}

// Where appends a list predicates to the WordListUpdate builder.
func (_u *WordListUpdateOne) Where(ps ...predicate.WordList) *WordListUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WordListUpdateOne) Select(field string, fields ...string) *WordListUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WordList entity.
func (_u *WordListUpdateOne) Save(ctx context.Context) (*WordList, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WordListUpdateOne) SaveX(ctx context.Context) *WordList {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WordListUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WordListUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WordListUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := wordlist.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "WordList.name": %w`, err)}
		}
	}
	return nil
}

func (_u *WordListUpdateOne) sqlSave(ctx context.Context) (_node *WordList, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wordlist.Table, wordlist.Columns, sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WordList.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wordlist.FieldID)
		for _, f := range fields {
			if !wordlist.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != wordlist.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(wordlist.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastUpdatedAt(); ok {
		_spec.SetField(wordlist.FieldLastUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.WordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   wordlist.WordsTable,
			Columns: wordlist.WordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(word.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWordsIDs(); len(nodes) > 0 && !_u.mutation.WordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   wordlist.WordsTable,
			Columns: wordlist.WordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(word.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   wordlist.WordsTable,
			Columns: wordlist.WordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(word.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   wordlist.GroupsTable,
			Columns: wordlist.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   wordlist.GroupsTable,
			Columns: wordlist.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   wordlist.GroupsTable,
			Columns: wordlist.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CompetitionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   wordlist.CompetitionsTable,
			Columns: wordlist.CompetitionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(competition.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCompetitionsIDs(); len(nodes) > 0 && !_u.mutation.CompetitionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   wordlist.CompetitionsTable,
			Columns: wordlist.CompetitionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(competition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CompetitionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   wordlist.CompetitionsTable,
			Columns: wordlist.CompetitionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(competition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WordList{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wordlist.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
