// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PhilAldridge/spell-api/ent/competition"
	"github.com/PhilAldridge/spell-api/ent/group"
	"github.com/PhilAldridge/spell-api/ent/school"
	"github.com/PhilAldridge/spell-api/ent/word"
	"github.com/PhilAldridge/spell-api/ent/wordlist"
)

// WordListCreate is the builder for creating a WordList entity.
type WordListCreate struct {
	config
	mutation *WordListMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *WordListCreate) SetName(v string) *WordListCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetLastUpdatedAt sets the "last_updated_at" field.
func (_c *WordListCreate) SetLastUpdatedAt(v time.Time) *WordListCreate {
	_c.mutation.SetLastUpdatedAt(v)
	return _c
}

// SetNillableLastUpdatedAt sets the "last_updated_at" field if the given value is not nil.
func (_c *WordListCreate) SetNillableLastUpdatedAt(v *time.Time) *WordListCreate {
	if v != nil {
		_c.SetLastUpdatedAt(*v)
	}
	return _c
}

// AddWordIDs adds the "words" edge to the Word entity by IDs.
func (_c *WordListCreate) AddWordIDs(ids ...int) *WordListCreate {
	_c.mutation.AddWordIDs(ids...)
	return _c
}

// AddWords adds the "words" edges to the Word entity.
func (_c *WordListCreate) AddWords(v ...*Word) *WordListCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddWordIDs(ids...)
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_c *WordListCreate) AddGroupIDs(ids ...int) *WordListCreate {
	_c.mutation.AddGroupIDs(ids...)
	return _c
}

// AddGroups adds the "groups" edges to the Group entity.
func (_c *WordListCreate) AddGroups(v ...*Group) *WordListCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddGroupIDs(ids...)
}

// SetSchoolID sets the "school" edge to the School entity by ID.
func (_c *WordListCreate) SetSchoolID(id int) *WordListCreate {
	_c.mutation.SetSchoolID(id)
	return _c
}

// SetNillableSchoolID sets the "school" edge to the School entity by ID if the given value is not nil.
func (_c *WordListCreate) SetNillableSchoolID(id *int) *WordListCreate {
	if id != nil {
		_c = _c.SetSchoolID(*id)
	}
	return _c
}

// SetSchool sets the "school" edge to the School entity.
func (_c *WordListCreate) SetSchool(v *School) *WordListCreate {
	return _c.SetSchoolID(v.ID)
}

// AddCompetitionIDs adds the "competitions" edge to the Competition entity by IDs.
func (_c *WordListCreate) AddCompetitionIDs(ids ...int) *WordListCreate {
	_c.mutation.AddCompetitionIDs(ids...)
	return _c
}

// AddCompetitions adds the "competitions" edges to the Competition entity.
func (_c *WordListCreate) AddCompetitions(v ...*Competition) *WordListCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCompetitionIDs(ids...)
}

// Mutation returns the WordListMutation object of the builder.
func (_c *WordListCreate) Mutation() *WordListMutation {
	return _c.mutation
}

// Save creates the WordList in the database.
func (_c *WordListCreate) Save(ctx context.Context) (*WordList, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WordListCreate) SaveX(ctx context.Context) *WordList {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WordListCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WordListCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WordListCreate) defaults() {
	if _, ok := _c.mutation.LastUpdatedAt(); !ok {
		v := wordlist.DefaultLastUpdatedAt
		_c.mutation.SetLastUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WordListCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "WordList.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := wordlist.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "WordList.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastUpdatedAt(); !ok {
		return &ValidationError{Name: "last_updated_at", err: errors.New(`ent: missing required field "WordList.last_updated_at"`)}
	}
	return nil
}

func (_c *WordListCreate) sqlSave(ctx context.Context) (*WordList, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WordListCreate) createSpec() (*WordList, *sqlgraph.CreateSpec) {
	var (
		_node = &WordList{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(wordlist.Table, sqlgraph.NewFieldSpec(wordlist.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(wordlist.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.LastUpdatedAt(); ok {
		_spec.SetField(wordlist.FieldLastUpdatedAt, field.TypeTime, value)
		_node.LastUpdatedAt = value
	}
	if nodes := _c.mutation.WordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   wordlist.WordsTable,
			Columns: wordlist.WordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(word.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   wordlist.GroupsTable,
			Columns: wordlist.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SchoolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wordlist.SchoolTable,
			Columns: []string{wordlist.SchoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(school.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.school_custom_word_lists = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CompetitionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   wordlist.CompetitionsTable,
			Columns: wordlist.CompetitionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(competition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WordListCreateBulk is the builder for creating many WordList entities in bulk.
type WordListCreateBulk struct {
	config
	err      error
	builders []*WordListCreate
}

// Save creates the WordList entities in the database.
func (_c *WordListCreateBulk) Save(ctx context.Context) ([]*WordList, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WordList, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WordListMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WordListCreateBulk) SaveX(ctx context.Context) []*WordList {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WordListCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WordListCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
