// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/PhilAldridge/spell-api/ent/school"
	"github.com/PhilAldridge/spell-api/ent/word"
)

// Word is the model entity for the Word schema.
type Word struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// LastUpdatedAt holds the value of the "last_updated_at" field.
	LastUpdatedAt time.Time `json:"last_updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WordQuery when eager-loading is set.
	Edges               WordEdges `json:"edges"`
	school_custom_words *int
	selectValues        sql.SelectValues
}

// WordEdges holds the relations/edges for other nodes in the graph.
type WordEdges struct {
	// WordLists holds the value of the word_lists edge.
	WordLists []*WordList `json:"word_lists,omitempty"`
	// School holds the value of the school edge.
	School *School `json:"school,omitempty"`
	// Results holds the value of the results edge.
	Results []*Result `json:"results,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// WordListsOrErr returns the WordLists value or an error if the edge
// was not loaded in eager-loading.
func (e WordEdges) WordListsOrErr() ([]*WordList, error) {
	if e.loadedTypes[0] {
		return e.WordLists, nil
	}
	return nil, &NotLoadedError{edge: "word_lists"}
}

// SchoolOrErr returns the School value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WordEdges) SchoolOrErr() (*School, error) {
	if e.School != nil {
		return e.School, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: school.Label}
	}
	return nil, &NotLoadedError{edge: "school"}
}

// ResultsOrErr returns the Results value or an error if the edge
// was not loaded in eager-loading.
func (e WordEdges) ResultsOrErr() ([]*Result, error) {
	if e.loadedTypes[2] {
		return e.Results, nil
	}
	return nil, &NotLoadedError{edge: "results"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Word) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case word.FieldID:
			values[i] = new(sql.NullInt64)
		case word.FieldName:
			values[i] = new(sql.NullString)
		case word.FieldLastUpdatedAt:
			values[i] = new(sql.NullTime)
		case word.ForeignKeys[0]: // school_custom_words
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Word fields.
func (_m *Word) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case word.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case word.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case word.FieldLastUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_updated_at", values[i])
			} else if value.Valid {
				_m.LastUpdatedAt = value.Time
			}
		case word.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field school_custom_words", value)
			} else if value.Valid {
				_m.school_custom_words = new(int)
				*_m.school_custom_words = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Word.
// This includes values selected through modifiers, order, etc.
func (_m *Word) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryWordLists queries the "word_lists" edge of the Word entity.
func (_m *Word) QueryWordLists() *WordListQuery {
	return NewWordClient(_m.config).QueryWordLists(_m)
}

// QuerySchool queries the "school" edge of the Word entity.
func (_m *Word) QuerySchool() *SchoolQuery {
	return NewWordClient(_m.config).QuerySchool(_m)
}

// QueryResults queries the "results" edge of the Word entity.
func (_m *Word) QueryResults() *ResultQuery {
	return NewWordClient(_m.config).QueryResults(_m)
}

// Update returns a builder for updating this Word.
// Note that you need to call Word.Unwrap() before calling this method if this Word
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Word) Update() *WordUpdateOne {
	return NewWordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Word entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Word) Unwrap() *Word {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Word is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Word) String() string {
	var builder strings.Builder
	builder.WriteString("Word(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("last_updated_at=")
	builder.WriteString(_m.LastUpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Words is a parsable slice of Word.
type Words []*Word
