// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/PhilAldridge/spell-api/ent/school"
	"github.com/PhilAldridge/spell-api/ent/wordlist"
)

// WordList is the model entity for the WordList schema.
type WordList struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// LastUpdatedAt holds the value of the "last_updated_at" field.
	LastUpdatedAt time.Time `json:"last_updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WordListQuery when eager-loading is set.
	Edges                    WordListEdges `json:"edges"`
	school_custom_word_lists *int
	selectValues             sql.SelectValues
}

// WordListEdges holds the relations/edges for other nodes in the graph.
type WordListEdges struct {
	// Words holds the value of the words edge.
	Words []*Word `json:"words,omitempty"`
	// Groups holds the value of the groups edge.
	Groups []*Group `json:"groups,omitempty"`
	// School holds the value of the school edge.
	School *School `json:"school,omitempty"`
	// Competitions holds the value of the competitions edge.
	Competitions []*Competition `json:"competitions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// WordsOrErr returns the Words value or an error if the edge
// was not loaded in eager-loading.
func (e WordListEdges) WordsOrErr() ([]*Word, error) {
	if e.loadedTypes[0] {
		return e.Words, nil
	}
	return nil, &NotLoadedError{edge: "words"}
}

// GroupsOrErr returns the Groups value or an error if the edge
// was not loaded in eager-loading.
func (e WordListEdges) GroupsOrErr() ([]*Group, error) {
	if e.loadedTypes[1] {
		return e.Groups, nil
	}
	return nil, &NotLoadedError{edge: "groups"}
}

// SchoolOrErr returns the School value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WordListEdges) SchoolOrErr() (*School, error) {
	if e.School != nil {
		return e.School, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: school.Label}
	}
	return nil, &NotLoadedError{edge: "school"}
}

// CompetitionsOrErr returns the Competitions value or an error if the edge
// was not loaded in eager-loading.
func (e WordListEdges) CompetitionsOrErr() ([]*Competition, error) {
	if e.loadedTypes[3] {
		return e.Competitions, nil
	}
	return nil, &NotLoadedError{edge: "competitions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WordList) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case wordlist.FieldID:
			values[i] = new(sql.NullInt64)
		case wordlist.FieldName:
			values[i] = new(sql.NullString)
		case wordlist.FieldLastUpdatedAt:
			values[i] = new(sql.NullTime)
		case wordlist.ForeignKeys[0]: // school_custom_word_lists
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WordList fields.
func (_m *WordList) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case wordlist.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case wordlist.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case wordlist.FieldLastUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_updated_at", values[i])
			} else if value.Valid {
				_m.LastUpdatedAt = value.Time
			}
		case wordlist.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field school_custom_word_lists", value)
			} else if value.Valid {
				_m.school_custom_word_lists = new(int)
				*_m.school_custom_word_lists = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WordList.
// This includes values selected through modifiers, order, etc.
func (_m *WordList) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryWords queries the "words" edge of the WordList entity.
func (_m *WordList) QueryWords() *WordQuery {
	return NewWordListClient(_m.config).QueryWords(_m)
}

// QueryGroups queries the "groups" edge of the WordList entity.
func (_m *WordList) QueryGroups() *GroupQuery {
	return NewWordListClient(_m.config).QueryGroups(_m)
}

// QuerySchool queries the "school" edge of the WordList entity.
func (_m *WordList) QuerySchool() *SchoolQuery {
	return NewWordListClient(_m.config).QuerySchool(_m)
}

// QueryCompetitions queries the "competitions" edge of the WordList entity.
func (_m *WordList) QueryCompetitions() *CompetitionQuery {
	return NewWordListClient(_m.config).QueryCompetitions(_m)
}

// Update returns a builder for updating this WordList.
// Note that you need to call WordList.Unwrap() before calling this method if this WordList
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WordList) Update() *WordListUpdateOne {
	return NewWordListClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WordList entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WordList) Unwrap() *WordList {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WordList is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WordList) String() string {
	var builder strings.Builder
	builder.WriteString("WordList(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("last_updated_at=")
	builder.WriteString(_m.LastUpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// WordLists is a parsable slice of WordList.
type WordLists []*WordList
