// Code generated by ent, DO NOT EDIT.

package school

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/PhilAldridge/spell-api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.School {
	return predicate.School(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.School {
	return predicate.School(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.School {
	return predicate.School(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.School {
	return predicate.School(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.School {
	return predicate.School(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.School {
	return predicate.School(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.School {
	return predicate.School(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.School {
	return predicate.School(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.School {
	return predicate.School(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.School {
	return predicate.School(sql.FieldEQ(FieldName, v))
}

// JoinCode applies equality check predicate on the "join_code" field. It's identical to JoinCodeEQ.
func JoinCode(v string) predicate.School {
	return predicate.School(sql.FieldEQ(FieldJoinCode, v))
}

// JoinCodeValidUntilTimestamp applies equality check predicate on the "join_code_valid_until_timestamp" field. It's identical to JoinCodeValidUntilTimestampEQ.
func JoinCodeValidUntilTimestamp(v time.Time) predicate.School {
	return predicate.School(sql.FieldEQ(FieldJoinCodeValidUntilTimestamp, v))
}

// LastUpdatedAt applies equality check predicate on the "last_updated_at" field. It's identical to LastUpdatedAtEQ.
func LastUpdatedAt(v time.Time) predicate.School {
	return predicate.School(sql.FieldEQ(FieldLastUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.School {
	return predicate.School(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.School {
	return predicate.School(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.School {
	return predicate.School(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.School {
	return predicate.School(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.School {
	return predicate.School(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.School {
	return predicate.School(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.School {
	return predicate.School(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.School {
	return predicate.School(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.School {
	return predicate.School(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.School {
	return predicate.School(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.School {
	return predicate.School(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.School {
	return predicate.School(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.School {
	return predicate.School(sql.FieldContainsFold(FieldName, v))
}

// JoinCodeEQ applies the EQ predicate on the "join_code" field.
func JoinCodeEQ(v string) predicate.School {
	return predicate.School(sql.FieldEQ(FieldJoinCode, v))
}

// JoinCodeNEQ applies the NEQ predicate on the "join_code" field.
func JoinCodeNEQ(v string) predicate.School {
	return predicate.School(sql.FieldNEQ(FieldJoinCode, v))
}

// JoinCodeIn applies the In predicate on the "join_code" field.
func JoinCodeIn(vs ...string) predicate.School {
	return predicate.School(sql.FieldIn(FieldJoinCode, vs...))
}

// JoinCodeNotIn applies the NotIn predicate on the "join_code" field.
func JoinCodeNotIn(vs ...string) predicate.School {
	return predicate.School(sql.FieldNotIn(FieldJoinCode, vs...))
}

// JoinCodeGT applies the GT predicate on the "join_code" field.
func JoinCodeGT(v string) predicate.School {
	return predicate.School(sql.FieldGT(FieldJoinCode, v))
}

// JoinCodeGTE applies the GTE predicate on the "join_code" field.
func JoinCodeGTE(v string) predicate.School {
	return predicate.School(sql.FieldGTE(FieldJoinCode, v))
}

// JoinCodeLT applies the LT predicate on the "join_code" field.
func JoinCodeLT(v string) predicate.School {
	return predicate.School(sql.FieldLT(FieldJoinCode, v))
}

// JoinCodeLTE applies the LTE predicate on the "join_code" field.
func JoinCodeLTE(v string) predicate.School {
	return predicate.School(sql.FieldLTE(FieldJoinCode, v))
}

// JoinCodeContains applies the Contains predicate on the "join_code" field.
func JoinCodeContains(v string) predicate.School {
	return predicate.School(sql.FieldContains(FieldJoinCode, v))
}

// JoinCodeHasPrefix applies the HasPrefix predicate on the "join_code" field.
func JoinCodeHasPrefix(v string) predicate.School {
	return predicate.School(sql.FieldHasPrefix(FieldJoinCode, v))
}

// JoinCodeHasSuffix applies the HasSuffix predicate on the "join_code" field.
func JoinCodeHasSuffix(v string) predicate.School {
	return predicate.School(sql.FieldHasSuffix(FieldJoinCode, v))
}

// JoinCodeEqualFold applies the EqualFold predicate on the "join_code" field.
func JoinCodeEqualFold(v string) predicate.School {
	return predicate.School(sql.FieldEqualFold(FieldJoinCode, v))
}

// JoinCodeContainsFold applies the ContainsFold predicate on the "join_code" field.
func JoinCodeContainsFold(v string) predicate.School {
	return predicate.School(sql.FieldContainsFold(FieldJoinCode, v))
}

// JoinCodeValidUntilTimestampEQ applies the EQ predicate on the "join_code_valid_until_timestamp" field.
func JoinCodeValidUntilTimestampEQ(v time.Time) predicate.School {
	return predicate.School(sql.FieldEQ(FieldJoinCodeValidUntilTimestamp, v))
}

// JoinCodeValidUntilTimestampNEQ applies the NEQ predicate on the "join_code_valid_until_timestamp" field.
func JoinCodeValidUntilTimestampNEQ(v time.Time) predicate.School {
	return predicate.School(sql.FieldNEQ(FieldJoinCodeValidUntilTimestamp, v))
}

// JoinCodeValidUntilTimestampIn applies the In predicate on the "join_code_valid_until_timestamp" field.
func JoinCodeValidUntilTimestampIn(vs ...time.Time) predicate.School {
	return predicate.School(sql.FieldIn(FieldJoinCodeValidUntilTimestamp, vs...))
}

// JoinCodeValidUntilTimestampNotIn applies the NotIn predicate on the "join_code_valid_until_timestamp" field.
func JoinCodeValidUntilTimestampNotIn(vs ...time.Time) predicate.School {
	return predicate.School(sql.FieldNotIn(FieldJoinCodeValidUntilTimestamp, vs...))
}

// JoinCodeValidUntilTimestampGT applies the GT predicate on the "join_code_valid_until_timestamp" field.
func JoinCodeValidUntilTimestampGT(v time.Time) predicate.School {
	return predicate.School(sql.FieldGT(FieldJoinCodeValidUntilTimestamp, v))
}

// JoinCodeValidUntilTimestampGTE applies the GTE predicate on the "join_code_valid_until_timestamp" field.
func JoinCodeValidUntilTimestampGTE(v time.Time) predicate.School {
	return predicate.School(sql.FieldGTE(FieldJoinCodeValidUntilTimestamp, v))
}

// JoinCodeValidUntilTimestampLT applies the LT predicate on the "join_code_valid_until_timestamp" field.
func JoinCodeValidUntilTimestampLT(v time.Time) predicate.School {
	return predicate.School(sql.FieldLT(FieldJoinCodeValidUntilTimestamp, v))
}

// JoinCodeValidUntilTimestampLTE applies the LTE predicate on the "join_code_valid_until_timestamp" field.
func JoinCodeValidUntilTimestampLTE(v time.Time) predicate.School {
	return predicate.School(sql.FieldLTE(FieldJoinCodeValidUntilTimestamp, v))
}

// LastUpdatedAtEQ applies the EQ predicate on the "last_updated_at" field.
func LastUpdatedAtEQ(v time.Time) predicate.School {
	return predicate.School(sql.FieldEQ(FieldLastUpdatedAt, v))
}

// LastUpdatedAtNEQ applies the NEQ predicate on the "last_updated_at" field.
func LastUpdatedAtNEQ(v time.Time) predicate.School {
	return predicate.School(sql.FieldNEQ(FieldLastUpdatedAt, v))
}

// LastUpdatedAtIn applies the In predicate on the "last_updated_at" field.
func LastUpdatedAtIn(vs ...time.Time) predicate.School {
	return predicate.School(sql.FieldIn(FieldLastUpdatedAt, vs...))
}

// LastUpdatedAtNotIn applies the NotIn predicate on the "last_updated_at" field.
func LastUpdatedAtNotIn(vs ...time.Time) predicate.School {
	return predicate.School(sql.FieldNotIn(FieldLastUpdatedAt, vs...))
}

// LastUpdatedAtGT applies the GT predicate on the "last_updated_at" field.
func LastUpdatedAtGT(v time.Time) predicate.School {
	return predicate.School(sql.FieldGT(FieldLastUpdatedAt, v))
}

// LastUpdatedAtGTE applies the GTE predicate on the "last_updated_at" field.
func LastUpdatedAtGTE(v time.Time) predicate.School {
	return predicate.School(sql.FieldGTE(FieldLastUpdatedAt, v))
}

// LastUpdatedAtLT applies the LT predicate on the "last_updated_at" field.
func LastUpdatedAtLT(v time.Time) predicate.School {
	return predicate.School(sql.FieldLT(FieldLastUpdatedAt, v))
}

// LastUpdatedAtLTE applies the LTE predicate on the "last_updated_at" field.
func LastUpdatedAtLTE(v time.Time) predicate.School {
	return predicate.School(sql.FieldLTE(FieldLastUpdatedAt, v))
}

// HasAdmins applies the HasEdge predicate on the "admins" edge.
func HasAdmins() predicate.School {
	return predicate.School(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, AdminsTable, AdminsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAdminsWith applies the HasEdge predicate on the "admins" edge with a given conditions (other predicates).
func HasAdminsWith(preds ...predicate.User) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		step := newAdminsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.School {
	return predicate.School(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroups applies the HasEdge predicate on the "groups" edge.
func HasGroups() predicate.School {
	return predicate.School(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GroupsTable, GroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupsWith applies the HasEdge predicate on the "groups" edge with a given conditions (other predicates).
func HasGroupsWith(preds ...predicate.Group) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		step := newGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCustomWords applies the HasEdge predicate on the "custom_words" edge.
func HasCustomWords() predicate.School {
	return predicate.School(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CustomWordsTable, CustomWordsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCustomWordsWith applies the HasEdge predicate on the "custom_words" edge with a given conditions (other predicates).
func HasCustomWordsWith(preds ...predicate.Word) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		step := newCustomWordsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCustomWordLists applies the HasEdge predicate on the "custom_word_lists" edge.
func HasCustomWordLists() predicate.School {
	return predicate.School(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CustomWordListsTable, CustomWordListsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCustomWordListsWith applies the HasEdge predicate on the "custom_word_lists" edge with a given conditions (other predicates).
func HasCustomWordListsWith(preds ...predicate.WordList) predicate.School {
	return predicate.School(func(s *sql.Selector) {
		step := newCustomWordListsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.School) predicate.School {
	return predicate.School(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.School) predicate.School {
	return predicate.School(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.School) predicate.School {
	return predicate.School(sql.NotPredicates(p))
}
