// Code generated by ent, DO NOT EDIT.

package word

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the word type in the database.
	Label = "word"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldLastUpdatedAt holds the string denoting the last_updated_at field in the database.
	FieldLastUpdatedAt = "last_updated_at"
	// EdgeWordLists holds the string denoting the word_lists edge name in mutations.
	EdgeWordLists = "word_lists"
	// EdgeSchool holds the string denoting the school edge name in mutations.
	EdgeSchool = "school"
	// EdgeResults holds the string denoting the results edge name in mutations.
	EdgeResults = "results"
	// Table holds the table name of the word in the database.
	Table = "words"
	// WordListsTable is the table that holds the word_lists relation/edge. The primary key declared below.
	WordListsTable = "word_list_words"
	// WordListsInverseTable is the table name for the WordList entity.
	// It exists in this package in order to avoid circular dependency with the "wordlist" package.
	WordListsInverseTable = "word_lists"
	// SchoolTable is the table that holds the school relation/edge.
	SchoolTable = "words"
	// SchoolInverseTable is the table name for the School entity.
	// It exists in this package in order to avoid circular dependency with the "school" package.
	SchoolInverseTable = "schools"
	// SchoolColumn is the table column denoting the school relation/edge.
	SchoolColumn = "school_custom_words"
	// ResultsTable is the table that holds the results relation/edge.
	ResultsTable = "results"
	// ResultsInverseTable is the table name for the Result entity.
	// It exists in this package in order to avoid circular dependency with the "result" package.
	ResultsInverseTable = "results"
	// ResultsColumn is the table column denoting the results relation/edge.
	ResultsColumn = "result_word"
)

// Columns holds all SQL columns for word fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldLastUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "words"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"school_custom_words",
}

var (
	// WordListsPrimaryKey and WordListsColumn2 are the table columns denoting the
	// primary key for the word_lists relation (M2M).
	WordListsPrimaryKey = []string{"word_list_id", "word_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultLastUpdatedAt holds the default value on creation for the "last_updated_at" field.
	DefaultLastUpdatedAt time.Time
)

// OrderOption defines the ordering options for the Word queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByLastUpdatedAt orders the results by the last_updated_at field.
func ByLastUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUpdatedAt, opts...).ToFunc()
}

// ByWordListsCount orders the results by word_lists count.
func ByWordListsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newWordListsStep(), opts...)
	}
}

// ByWordLists orders the results by word_lists terms.
func ByWordLists(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWordListsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySchoolField orders the results by school field.
func BySchoolField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSchoolStep(), sql.OrderByField(field, opts...))
	}
}

// ByResultsCount orders the results by results count.
func ByResultsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newResultsStep(), opts...)
	}
}

// ByResults orders the results by results terms.
func ByResults(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newResultsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newWordListsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WordListsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, WordListsTable, WordListsPrimaryKey...),
	)
}
func newSchoolStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SchoolInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SchoolTable, SchoolColumn),
	)
}
func newResultsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ResultsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ResultsTable, ResultsColumn),
	)
}
